'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const crypto=require('node:crypto');
const root=path.resolve(__dirname,'../..');let count=0,bytes=0;
const required=['blackout-protocol.html','blackout/style.css','blackout/missions.js','blackout/world.js','blackout/core.js','blackout/save.js','blackout/meta.js','blackout/audio.js','blackout/gamepad.js','blackout/icons.js','blackout/render.js','blackout/game.js','blackout/vendor/phaser.js','blackout/vendor/LICENSE.md','blackout/assets/characters.png','blackout/assets/characters.json','blackout/assets/props.png','blackout/assets/props.json','blackout/assets/cover.svg','blackout/assets/helicopter.svg','blackout/ASSET_MANIFEST.md','blackout/GAME_DESIGN.md','blackout/ANIMATION_SPEC.md','blackout/CAMPAIGN_PLAN.md','blackout/TEST_REPORT.md','blackout/DEVELOPMENT_PROGRESS.md'];
for(const file of required){assert(fs.existsSync(path.join(root,file)),`Missing deployable file: ${file}`);count++;bytes+=fs.statSync(path.join(root,file)).size;}
const html=fs.readFileSync(path.join(root,'blackout-protocol.html'),'utf8');for(const m of html.matchAll(/(?:src|href)="(blackout\/[^"?#]+)"/g))assert(fs.existsSync(path.join(root,m[1])),`Broken HTML reference ${m[1]}`);
const audio=fs.readFileSync(path.join(root,'blackout/audio.js'),'utf8');const files=audio.match(/const files=\[([^\]]+)\]/)[1];for(const match of files.matchAll(/'([^']+)'/g)){const file=path.join(root,'blackout/assets/audio',match[1]);assert(fs.existsSync(file),`Missing audio: ${file}`);count++;bytes+=fs.statSync(file).size;}
const atlas=JSON.parse(fs.readFileSync(path.join(root,'blackout/assets/characters.json')));assert.equal(Object.keys(atlas.frames).length,365);for(const type of ['rifle','handgun','shotgun'])for(const state of ['idle','move','shoot','reload'])assert(atlas.frames[`${type}/${state}/0`]);assert(atlas.frames['feet/strafe_left/19']);assert(atlas.frames['knife/meleeattack/14']);
for(const entry of JSON.parse(fs.readFileSync(path.join(root,'blackout/assets/integrity.json'))).files){const data=fs.readFileSync(path.join(root,'blackout/assets',entry.file));assert.equal(data.length,entry.bytes,`Asset size mismatch: ${entry.file}`);assert.equal(crypto.createHash('sha256').update(data).digest('hex'),entry.sha256,`Asset hash mismatch: ${entry.file}`);}
assert(fs.readFileSync(path.join(root,'library.js'),'utf8').includes('blackout-protocol.html'));assert(fs.readFileSync(path.join(root,'netlify.toml'),'utf8').includes('publish = "dist"'));assert(!/https?:\/\//.test(html.match(/<script[^>]+src[^>]+>/g).join('')),'Runtime scripts must be local');
console.log(`${count} static files verified; ${(bytes/1024/1024).toFixed(2)} MiB for entry, engine, atlases, essential sounds and documentation. No backend or compilation required.`);
