'use strict';
const {chromium}=require('playwright'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),siteRoot=process.argv.includes('--production')?path.join(root,'dist'):root,results=[],errors=[],requests=[];
const server=http.createServer((req,res)=>{let file;try{file=path.resolve(siteRoot,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));}catch{res.writeHead(400).end();return;}if(file===siteRoot)file=path.join(siteRoot,'index.html');if(!file.startsWith(siteRoot+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end();return;}const types={'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.svg':'image/svg+xml','.ogg':'audio/ogg','.wav':'audio/wav','.woff2':'font/woff2'};res.setHeader('Content-Type',types[path.extname(file)]||'application/octet-stream');res.end(data);});});
let browser;
async function check(name,fn){await fn();results.push(name);console.log('PASS',name);}
async function ready(page,url){await page.goto(url,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.getElementById('loading')?.hidden,{timeout:30000});}
const snapshot=page=>page.evaluate(()=>BPApp.snapshot());
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`,url=base+'/blackout-protocol.html';browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1366,height:768}}),page=await context.newPage();
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().startsWith(base)&&r.status()>=400&&!r.url().includes('favicon'))requests.push(r.url());});fs.mkdirSync(path.join(root,'blackout/qa'),{recursive:true});
await check('title loads every local gameplay asset and provides campaign and range',async()=>{await ready(page,url);assert.equal(await page.locator('#continue').innerText(),'DEPLOY INTO CAMPAIGN\n↗');await page.screenshot({path:path.join(root,'blackout/qa/title.png')});});
await check('real WASD input accelerates, sprints, slides and recovers',async()=>{await page.click('#training');await page.waitForFunction(()=>BPApp.snapshot().mode==='playing');const before=await snapshot(page);await page.keyboard.down('ShiftLeft');await page.keyboard.down('KeyD');await page.waitForFunction(x=>BPApp.snapshot().x>x+95,before.x);await page.keyboard.press('ControlLeft');await page.waitForFunction(()=>BPApp.snapshot().state==='slide');const slide=await snapshot(page);assert(slide.stamina<100);await page.keyboard.up('ShiftLeft');await page.keyboard.up('KeyD');await page.waitForFunction(()=>BPApp.snapshot().state==='idle');assert((await snapshot(page)).x>before.x+175);});
await check('real sprint to slide to vault earns perfect flow and crosses cover',async()=>{await page.keyboard.press('Escape');await page.click('#retry');await page.keyboard.down('KeyW');await page.waitForFunction(()=>BPApp.snapshot().y<390);await page.keyboard.up('KeyW');await page.waitForTimeout(250);await page.keyboard.down('KeyD');await page.waitForFunction(()=>BPApp.snapshot().x>700);await page.keyboard.up('KeyD');await page.waitForTimeout(250);await page.keyboard.down('ShiftLeft');await page.keyboard.down('KeyS');await page.waitForFunction(()=>BPApp.snapshot().y>412);await page.keyboard.press('ControlLeft');await page.waitForFunction(()=>BPApp.snapshot().state==='slide');await page.waitForTimeout(85);await page.keyboard.press('KeyE');await page.waitForFunction(()=>BPApp.snapshot().state==='vault');await page.keyboard.up('KeyS');await page.keyboard.up('ShiftLeft');await page.waitForFunction(()=>BPApp.snapshot().state==='idle');const s=await snapshot(page);assert(s.flows>=1);assert(s.y>485);await page.keyboard.press('Escape');await page.click('#retry');});
await check('directional roll and sprint dive invoke different animation states',async()=>{await page.keyboard.down('KeyS');await page.keyboard.press('Space');await page.waitForFunction(()=>BPApp.snapshot().state==='roll');await page.keyboard.up('KeyS');await page.waitForTimeout(550);await page.keyboard.down('ShiftLeft');await page.keyboard.down('KeyW');await page.keyboard.press('Space');await page.waitForFunction(()=>BPApp.snapshot().state==='dive');await page.keyboard.up('KeyW');await page.keyboard.up('ShiftLeft');await page.waitForFunction(()=>BPApp.snapshot().state==='idle');});
await check('mouse aim, rifle fire, reload, shotgun selection and synchronized sampled audio',async()=>{await page.mouse.move(1050,450);const before=await snapshot(page);await page.mouse.down();await page.waitForFunction(n=>BPApp.snapshot().ammo<n,before.ammo);await page.mouse.up();await page.keyboard.press('KeyR');await page.waitForFunction(()=>BPApp.snapshot().reload>0);await page.waitForFunction(()=>BPApp.snapshot().reload<=0);assert.equal((await snapshot(page)).ammo,30);await page.keyboard.press('Digit2');await page.waitForFunction(()=>BPApp.snapshot().weapon==='shotgun');await page.mouse.down();await page.waitForFunction(()=>BPApp.snapshot().ammo===5);await page.mouse.up();const shot=await snapshot(page);assert(shot.audioUnlocked);assert.equal(shot.audioContext,'running');});
await check('grenades explode and melee transitions enter live animation states',async()=>{await page.keyboard.press('KeyG');await page.waitForFunction(()=>BPApp.snapshot().grenades===8);await page.waitForTimeout(1700);assert((await snapshot(page)).particles>0);await page.keyboard.press('KeyF');await page.waitForFunction(()=>BPApp.snapshot().state==='melee');await page.waitForTimeout(450);await page.screenshot({path:path.join(root,'blackout/qa/combat.png')});});
await check('pause freezes simulation and clears held fire and movement',async()=>{await page.keyboard.down('KeyD');await page.mouse.down();await page.keyboard.press('Escape');const a=await snapshot(page);await page.waitForTimeout(500);assert.equal((await snapshot(page)).time,a.time);await page.keyboard.up('KeyD');await page.mouse.up();await page.click('#resume');const ammo=(await snapshot(page)).ammo;await page.waitForTimeout(350);assert.equal((await snapshot(page)).ammo,ammo);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));assert.equal((await snapshot(page)).mode,'paused');});
await check('settings rebind an action, persist on reload and preserve the campaign save',async()=>{await page.click('#pause-settings');await page.click('[data-action="reload"]');await page.keyboard.press('KeyT');await page.selectOption('#difficulty','story');await page.locator('#flash').check();await page.locator('#settings .primary').click();let s=await snapshot(page);assert.equal(s.save.settings.bindings.reload,'KeyT');assert.equal(s.save.settings.flash,true);assert.equal(s.save.checkpoint,null);await ready(page,url);await page.click('#training');s=await snapshot(page);assert.equal(s.save.settings.bindings.reload,'KeyT');});
await check('all eight firearm choices are usable through the range equipment menu',async()=>{for(const key of ['pistol','smg','precision','lmg','launcher','rocket','rifle','shotgun']){await page.click('#settings-button');await page.selectOption('#range-weapon',key);await page.locator('#settings .primary').click();await page.click('#resume');assert.equal((await snapshot(page)).weapon,key);await page.mouse.move(1100,450);const before=(await snapshot(page)).ammo;await page.mouse.down();await page.waitForFunction(n=>BPApp.snapshot().ammo<n,before);await page.mouse.up();}await page.keyboard.press('Escape');await page.click('#exit');});
await check('campaign checkpoint fixtures restore position, story equipment and continue label',async()=>{await page.evaluate(()=>{localStorage.setItem('blackout-protocol-progress',JSON.stringify({version:1,checkpoint:{stage:2,time:100,kills:7},settings:{difficulty:'story',flash:true}}));});await ready(page,url);assert((await page.locator('#continue').innerText()).includes('CONTINUE CAMPAIGN'));await page.click('#continue');const s=await snapshot(page);assert.equal(s.stage,2);assert.equal(s.x,1470);assert.equal(s.y,1150);assert.equal(s.grenades,3);await page.keyboard.press('Digit2');await page.waitForFunction(()=>BPApp.snapshot().weapon==='shotgun');await page.screenshot({path:path.join(root,'blackout/qa/courtyard-route.png')});await page.keyboard.press('Escape');await page.click('#exit');});
await check('corrupt saves and offline fonts do not block play',async()=>{await page.evaluate(()=>localStorage.setItem('blackout-protocol-progress','invalid json'));await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.route('https://fonts.gstatic.com/**',r=>r.abort());await ready(page,url);await page.click('#continue');assert.equal((await snapshot(page)).stage,0);await page.screenshot({path:path.join(root,'blackout/qa/crash.png')});});
await check('full opening mission and saved ending complete through real keyboard and mouse input',async()=>{await page.click('#settings-button');await page.selectOption('#difficulty','story');await page.locator('#settings .primary').click();await page.click('#resume');const {play}=require('./browser-walkthrough.cjs');const outcome=await play(page,async name=>page.screenshot({path:path.join(root,'blackout/qa',name+'.png')}));assert.equal(outcome.world.stats.kills,15);assert.equal((await snapshot(page)).save.completed,true);assert(await page.locator('#ending').isVisible());await page.screenshot({path:path.join(root,'blackout/qa/ending.png')});});
await check('viewport resizing keeps readable menus within the viewport',async()=>{await page.click('#ending-menu');await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(root,'blackout/qa/small-screen.png')});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.setViewportSize({width:1366,height:768});});
await check('arcade integration exposes the new route and leaves existing cards',async()=>{const library=await context.newPage();await library.goto(base);assert.equal(await library.locator('.game-card').count(),8);assert.equal(await library.locator('.game-link[href="blackout-protocol.html"]').count(),1);await library.screenshot({path:path.join(root,'blackout/qa/library.png')});await library.close();});
await check('blocked browser storage degrades to session-only progress',async()=>{const isolated=await browser.newContext({viewport:{width:1280,height:720}});await isolated.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new DOMException('Blocked','SecurityError');}}));const blocked=await isolated.newPage();blocked.on('pageerror',e=>errors.push(e.message));await ready(blocked,url);await blocked.click('#continue');assert.equal((await snapshot(blocked)).mode,'playing');await isolated.close();});
await page.bringToFront();await page.click('#training');await page.waitForTimeout(1500);const fps=[];for(let i=0;i<10;i++){await page.waitForTimeout(350);fps.push((await snapshot(page)).averageFps);}const sorted=[...fps].sort((a,b)=>a-b);const performance={samples:fps.map(n=>Math.round(n)),medianFps:Math.round(sorted[5]),viewport:'1366 × 768',note:'Headless Chromium on this Windows host; not a hardware FPS guarantee.'};
assert.deepEqual(errors,[],'Uncaught browser errors');assert.deepEqual(requests,[],'Broken local resource requests');const report={passed:results.length,results,errors,requests,performance};fs.writeFileSync(path.join(root,'blackout/qa/browser-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report.performance));console.log(`${results.length} real-browser checks passed.`);
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.close();});
