'use strict';
const assert=require('node:assert/strict'),Core=require('../core.js'),World=require('../world.js'),Save=require('../save.js');
let passed=0;
function test(name,fn){try{fn();passed++;console.log('PASS',name);}catch(e){console.error('FAIL',name);throw e;}}
function ticks(s,n,input={}){for(let i=0;i<n;i++)Core.step(s,typeof input==='function'?input(i):input);return s;}
function range(){const s=Core.create({training:true});s.enemies=[];s.events=[];return s;}
test('fixed simulation is reproducible with the same seed and input',()=>{const a=range(),b=range();const inputs=i=>({mx:i<180?1:-1,my:i%100>50?1:0,sprint:i<150,fire:i%4===0,aimX:1550,aimY:620});ticks(a,300,inputs);ticks(b,300,inputs);assert.deepEqual(a,b);});
test('movement responds in one step, reaches sprint speed, and brakes',()=>{const s=range();Core.step(s,{mx:1,sprint:true});assert(s.player.vx>60);ticks(s,50,{mx:1,sprint:true});assert(s.player.vx>350);ticks(s,30);assert(Math.abs(s.player.vx)<1);});
test('diagonal speed is normalized',()=>{const a=range(),b=range();ticks(a,30,{mx:1});ticks(b,30,{mx:1,my:1});assert(Math.abs(Math.hypot(a.player.vx,a.player.vy)-Math.hypot(b.player.vx,b.player.vy))<.1);});
test('slide preserves momentum and loses speed to friction',()=>{const s=range();ticks(s,35,{mx:1,sprint:true});Core.step(s,{mx:1,sprint:true,slide:true});assert.equal(s.player.state,'slide');const speed=s.player.vx;ticks(s,20,{mx:1,fire:true,aimX:1500,aimY:s.player.y});assert.equal(s.player.state,'slide');assert(s.player.vx<speed&&s.player.vx>200);assert(s.stats.shots>0);});
test('roll immunity matches active frames, costs stamina, and has recovery',()=>{const s=range();Core.step(s,{mx:1,roll:true});assert.equal(s.player.state,'roll');assert(s.player.stamina<71);assert(Core.damagePlayer(s,10,0,0));s.player.iframes=0;ticks(s,10);assert(!Core.damagePlayer(s,10,0,0));ticks(s,25);s.player.iframes=0;assert(Core.damagePlayer(s,10,0,0));ticks(s,18);assert.equal(s.player.state,'idle');});
test('sprint + roll creates a longer committed dive',()=>{const a=range(),b=range();Core.step(a,{mx:1,sprint:true,roll:true});Core.step(b,{mx:1,roll:true});assert.equal(a.player.state,'dive');ticks(a,30);ticks(b,30);assert(a.player.x>b.player.x);assert(a.player.duration>b.player.duration);});
test('slide to vault rewards its timing window and clears the collider',()=>{const s=range();s.player.x=715;s.player.y=402;s.player.state='slide';s.player.age=.16;s.player.vy=380;s.player.angle=Math.PI/2;s.player.stamina=80;assert(Core.vault(s,{mx:0,my:1}));assert.equal(s.player.state,'vault');assert.equal(s.stats.flows,1);ticks(s,40,{my:1});assert(s.player.y>490);assert(Core.clearAt(s,s.player.x,s.player.y,16));});
test('solid cover blocks travel while a slide can pass under designated cover',()=>{const s=range();s.player.x=940;s.player.y=818;Core.move(s,s.player,0,100);assert(s.player.y<850);s.player.state='slide';Core.move(s,s.player,0,100);assert(s.player.y>880);});
test('vault refuses a blocked landing point',()=>{const s=range();s.player.x=710;s.player.y=410;s.walls.push({id:'block',x:620,y:475,w:200,h:100,dead:false});assert(!Core.vault(s,{mx:0,my:1}));});
test('every firearm has distinct cadence, damage, capacity, recoil and movement rules',()=>{const definitions=Object.values(World.weapons);assert.equal(definitions.length,8);assert.equal(new Set(definitions.map(w=>JSON.stringify([w.capacity,w.rate,w.damage,w.reload,w.spread]))).size,8);for(const key of Object.keys(World.weapons)){const s=range();s.player.slots[0]=key;Core.step(s,{fire:true,aimX:1600,aimY:625});assert.equal(s.stats.shots,1);assert.equal(s.player.ammo[key],World.weapons[key].capacity-1);assert(s.projectiles.filter(p=>p.active).length>=World.weapons[key].pellets);}});
test('reload transfers actual reserve ammunition without creating ammo',()=>{const s=range();s.player.ammo.rifle=2;s.player.reserve.rifle=7;Core.step(s,{reload:true});assert(s.player.reload>0);ticks(s,240);assert.equal(s.player.ammo.rifle,9);assert.equal(s.player.reserve.rifle,0);});
test('shots hit enemies along swept segments, including a high speed precision round',()=>{const s=range();const e={id:'target',x:650,y:625,radius:16,hp:70,maxHp:70,angle:0,type:'infantry',dead:false,zone:0,active:false,seen:0,cooldown:100,stagger:0,reload:0,vx:0,vy:0};s.enemies=[e];s.player.slots[0]='precision';Core.step(s,{fire:true,aimX:e.x,aimY:e.y});ticks(s,18);assert(e.dead);assert.equal(s.stats.kills,1);});
test('walls intercept shots before targets',()=>{const s=range();s.walls.push({id:'shield',x:510,y:550,w:30,h:200,hp:Infinity});const e={id:'target',x:600,y:625,radius:16,hp:70,maxHp:70,angle:0,type:'infantry',dead:false,zone:0,active:false,seen:0,cooldown:100,stagger:0,reload:0};s.enemies=[e];Core.step(s,{fire:true,aimX:e.x,aimY:e.y});ticks(s,50);assert.equal(e.hp,70);});
test('knife active frames cause one hit, combos escalate, heavy attacks break shields',()=>{const s=range();const e={id:'target',x:s.player.x+50,y:s.player.y,radius:16,hp:300,maxHp:300,angle:Math.PI,type:'shield',dead:false,zone:0,active:false,seen:0,cooldown:100,stagger:0,reload:0};s.enemies=[e];Core.melee(s,true);ticks(s,30);assert(e.hp<=205);const hp=e.hp;ticks(s,30);assert.equal(e.hp,hp);});
test('explosions chain through barrels and remove physical obstructions',()=>{const s=range();s.walls=[{id:'a',x:450,y:625,w:30,h:38,kind:'barrel',hp:20,maxHp:20,dead:false},{id:'b',x:490,y:625,w:30,h:38,kind:'barrel',hp:20,maxHp:20,dead:false},{id:'c',x:530,y:625,w:50,h:50,kind:'crate',hp:40,maxHp:40,dead:false}];Core.explode(s,465,640,150,160);assert(s.walls.every(w=>w.dead));assert(s.events.filter(e=>e.type==='explosion').length>=3);assert(Core.clearAt(s,550,650,16));});
test('healing consumes supplies once and damage interrupts it',()=>{const s=range();s.player.health=30;Core.step(s,{gadget:true});ticks(s,150);assert.equal(s.player.health,80);assert.equal(s.player.stims,4);Core.step(s,{gadget:true});assert(Core.damagePlayer(s,20,0,0));ticks(s,110);assert.equal(s.player.stims,4);assert(s.player.health<80);});
test('AI cannot acquire targets through solid buildings',()=>{const s=Core.create();const e=s.enemies[0];s.player.x=300;s.player.y=160;ticks(s,60);assert.equal(e.active,false);assert.equal(e.seen,0);});
test('ranged enemies visibly wind up attacks and have reload windows',()=>{const s=Core.create({training:true});s.walls=[];s.enemies=[s.enemies[0]];const e=s.enemies[0];e.x=650;e.y=625;e.cooldown=0;Core.step(s,{});assert(e.attack>0);assert.equal(s.projectiles.filter(p=>p.active).length,0);ticks(s,50);assert(s.events.some(e=>e.type==='shot'&&e.enemy));e.clip=4;e.cooldown=0;e.attack=0;ticks(s,60);assert(e.reload>0);});
test('story equipment is locked until the supply cache, training never changes campaign',()=>{const s=Core.create();assert(!s.player.unlocks.includes('shotgun'));Core.step(s,{slot:1});assert.equal(s.player.slot,0);s.enemies=[];s.stage=1;s.player.x=s.map.objectives[1].x;s.player.y=s.map.objectives[1].y;Core.interact(s,{mx:0,my:1});assert.equal(s.stage,2);assert(s.player.unlocks.includes('shotgun'));assert.equal(s.player.grenades,3);assert.deepEqual(s.checkpoint.stage,2);assert(Core.create({training:true}).player.unlocks.includes('rocket'));});
test('director warns before spawning and avoids the immediate player space',()=>{const s=Core.create({checkpoint:{stage:3}});Core.step(s,{});assert(s.spawnWarnings.length>0);assert.equal(s.enemies.length,0);assert(s.spawnWarnings.every(w=>Core.distance(w,s.player)>=340));ticks(s,280);assert(s.enemies.length>0);assert.equal(s.spawnWarnings.length,0);});
test('checkpoint restoration uses authored safe positions and unlocks',()=>{for(let stage=0;stage<=3;stage++){const s=Core.create({checkpoint:{stage,time:125,kills:6}});assert(Core.clearAt(s,s.player.x,s.player.y,16));assert.equal(s.time,125);assert.equal(s.stats.kills,6);assert.equal(s.player.unlocks.includes('shotgun'),stage>=2);}});
test('versioned saves recover from corruption, invalid versions, duplicate bindings and blocked storage',()=>{assert.deepEqual(Save.decode('{'),Save.defaults());assert.deepEqual(Save.decode('{"version":999}'),Save.defaults());const a=Save.decode(JSON.stringify({version:1,checkpoint:{stage:2,time:12},settings:{volume:9,bindings:{up:'KeyD'}}}));assert.equal(a.settings.volume,1);assert.deepEqual(a.settings.bindings,Save.bindings);assert(a.unlocks.includes('shotgun'));assert.equal(Save.load({getItem(){throw Error('blocked')}}).version,1);assert.equal(Save.write({setItem(){throw Error('blocked')}},a),false);});
test('projectile capacity stays bounded during sustained heavy fire',()=>{const s=range();s.player.slots[0]='lmg';ticks(s,10000,i=>({fire:true,reload:i%200===0,aimX:1700,aimY:650}));assert.equal(s.projectiles.length,192);assert(s.events.length<=256);assert(s.pickups.length<30);});
test('melee hitstop buffers a roll request instead of dropping the control edge',()=>{const s=range();s.hitstop=.025;Core.step(s,{roll:true,mx:1});assert.notEqual(s.player.state,'roll');ticks(s,5,{mx:1});assert.equal(s.player.state,'roll');});
test('a protruding muzzle cannot fire through thin cover',()=>{const s=range();s.walls.push({id:'thin',x:s.player.x+24,y:580,w:6,h:90,hp:Infinity,kind:'building'});const e={id:'target',x:600,y:625,radius:16,hp:70,maxHp:70,angle:0,type:'infantry',dead:false,zone:0,active:false,seen:0,cooldown:100,stagger:0,reload:0};s.enemies=[e];Core.step(s,{fire:true,aimX:e.x,aimY:e.y});ticks(s,40);assert.equal(e.hp,70);});
test('death ends control updates and extraction reaches a real completion event',()=>{const s=range();s.player.armor=0;Core.damagePlayer(s,300,0,0);assert(s.dead);const x=s.player.x;Core.step(s,{mx:1});assert.equal(s.player.x,x);const ending=Core.create({checkpoint:{stage:3}});ending.enemies=[];ending.stage=4;ending.player.x=1990;ending.player.y=1625;Core.interact(ending,{mx:0,my:0});assert(ending.cinematic>0);ticks(ending,740);assert(ending.completed);assert(ending.events.some(e=>e.type==='complete'));});
test('training respawns warn first and reuse enemy records without accumulating duplicates',()=>{const s=Core.create({training:true});s.enemies.forEach(e=>{e.dead=true;e.deathAge=6;});s.director.clock=8.99;Core.step(s);Core.step(s);assert(s.spawnWarnings.length>0);assert(s.enemies.every(e=>e.dead));const count=s.enemies.length;ticks(s,290);assert.equal(s.enemies.length,count);assert(s.enemies.some(e=>!e.dead));assert.equal(new Set(s.enemies.map(e=>e.id)).size,count);});
console.log(`\n${passed} core checks passed.`);
