// Writes bloodoath/FRAME_DATA.md from the fighter data, so the published numbers can never drift from the game.
// Usage: node bloodoath/tools/frame-data.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ROSTER } from '../data/roster.js';
import boss from '../data/malgrave.js';

const INPUT = id => (id === 'throw' ? 'T' : id === 'breaker' ? 'B+X (hit)' : id === 'super' ? 'H+S' : id.startsWith('j') ? 'air ' + id.slice(1) : id.replace('2', '↓').replace('6', '→').replace('4', '←').replace('5', ''));
const onBlock = m => (m.level === 'throw' || !m.box || !m.blockstun ? '—' : String(m.blockstun - m.active - m.recovery + 1).replace(/^(\d)/, '+$1'));
const traits = m => [m.launch && m.level !== 'throw' ? 'launches' : '', m.knockdown ? 'knocks down' : '', m.bounce ? 'ground bounce' : '', m.armor ? `armour ×${m.armor.hits} (f${m.armor.from}–${m.armor.to})` : '', m.invuln ? `invulnerable f${m.invuln[0]}–${m.invuln[1]}` : '', m.counter ? 'counter' : '', m.command ? 'command grab' : '', m.status?.burn ? 'burn' : '', m.status?.bleed ? 'bleed' : '', m.status?.chill ? 'chill' : '', m.status?.freeze ? 'freeze' : '', m.cancel ? 'cancels: ' + m.cancel.join('/') : '', m.cine ? 'cinematic on hit' : ''].filter(Boolean).join('; ');
const dmg = m => { const shot = (m.events || []).find(e => e.type === 'projectile'); return m.cine ? `${m.damage} + ${m.cine.hits.reduce((n, h) => n + h[1], 0)}` : shot ? shot.def.damage : m.damage || '—'; };
const lvl = m => { const shot = (m.events || []).find(e => e.type === 'projectile'); return shot ? shot.def.level + ' (projectile)' : m.box || m.level === 'throw' ? m.level : '—'; };

let out = '# BLOOD OATH — Frame data\n\nGenerated by `node bloodoath/tools/frame-data.mjs` from `bloodoath/data/`. Do not edit by hand.\n\nOne frame is 1/60 s. **Startup** is the frame the move first hits on (a 5-frame move connects on its 5th frame). **On block** is the attacker\'s advantage when the first active frame is blocked; a negative number is how many frames the defender gets to act first. Damage is before combo scaling.\n';
for (const f of [...ROSTER, boss]) {
  out += `\n## ${f.name} — ${f.title}${f.boss ? ' (boss, not selectable)' : ''}\n\nHealth ${f.health} · walk ${f.walkF}/${f.walkB} px per frame · forward dash ${f.dashF.frames}f · back dash ${f.dashB.frames}f (${f.dashB.inv}f invulnerable)${f.ward ? ` · Oath Ward ${f.ward.max} charges, one per ${f.ward.every}f (${f.ward.rage}f below ${f.ward.rageBelow * 100}% health)` : ''}\n\n| Move | Input | Hits | Startup | Active | Recovery | On block | Damage | Notes |\n|---|---|---|---|---|---|---|---|---|\n`;
  for (const [id, m] of Object.entries(f.moves)) out += `| ${m.name}${m.hidden ? ' (follow-up)' : ''} | ${INPUT(id)} | ${lvl(m)} | ${m.startup} | ${m.active} | ${m.recovery} | ${onBlock(m)} | ${dmg(m)} | ${traits(m)} |\n`;
}
const file = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../FRAME_DATA.md'); fs.writeFileSync(file, out); console.log('wrote', path.relative(process.cwd(), file));
