(() => {
 'use strict';
 let storage;try{storage=window.localStorage;}catch{storage=null;}
 const $=id=>document.getElementById(id),save=BPSave.load(storage),settings=save.settings,pressed=new Set(),held=new Set();
 const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced){settings.shake=0;settings.flash=true;}
 let scene=null,mode='menu',bindingTarget=null,lastHud=0,radioUntil=0,toastUntil=0,mouseFire=false,mouseAim=false,hadSaveFailure=false;
 const labels={up:'Move up',down:'Move down',left:'Move left',right:'Move right',sprint:'Sprint',roll:'Roll / dive',slide:'Slide',interact:'Interact / vault',reload:'Reload',gadget:'Stim injector',melee:'Melee',grenade:'Frag grenade',slot1:'Weapon 1',slot2:'Weapon 2',slot3:'Weapon 3'};
 const pad=new BPGamepad(),padTaps=new Set(),PAD_REACH=300,PAD_TURN=14,ASSIST_TURN=45,ASSIST_CONE=.7,ASSIST_BREAK=.6,padActionLabel=key=>labels[key]||{fire:'Fire',aim:'Steady aim'}[key];
 let padState=null,padActive=false,padAngle=0,padTarget=0,padAimIdle=0,padMenuStick=0,padBindingTarget=null,padLock=null,padLockLost=0,padReach=PAD_REACH;
 function displayKey(code){return code.replace(/^Key|^Digit/,'').replace('Left','').replace('Right','');}
 function keyLabel(action){return padActive?BPGamepad.labels[settings.padBindings[action]]:displayKey(settings.bindings[action]);}
 function strip(){$('controls-strip').textContent=`${keyLabel('sprint')} SPRINT / ${keyLabel('slide')} SLIDE / ${keyLabel('roll')} ROLL / ${keyLabel('interact')} VAULT / ${keyLabel('reload')} RELOAD / ${keyLabel('melee')} MELEE / ${padActive?'START':'ESC'} PAUSE`;}
 function setPadActive(value){padActive=value;document.body.classList.toggle('pad',value);if(value&&scene?.sim)padAngle=padTarget=scene.sim.player.angle;padAimIdle=0;strip();}
 function padStatus(){const name=settings.gamepad?pad.name:null;$('gamepad-status').textContent=!BPGamepad.supported?'NOT SUPPORTED IN THIS BROWSER':!settings.gamepad?'OFF':name?name.slice(0,34):'PRESS ANY BUTTON ON THE CONTROLLER';}
 function persist(){const ok=BPSave.write(storage,save);if(!ok&&!hadSaveFailure){hadSaveFailure=true;toast('STORAGE UNAVAILABLE / CHECKPOINTS LAST THIS SESSION');}return ok;}
 function clearInput(){held.clear();pressed.clear();padTaps.clear();padState=null;padLock=null;mouseFire=false;mouseAim=false;}
 function toast(text,duration=2.5){$('toast').textContent=text;$('toast').style.opacity='1';toastUntil=performance.now()+duration*1000;}
 function radio(e){$('radio-speaker').textContent=e.speaker;$('radio-text').textContent=e.text;$('radio').hidden=false;radioUntil=scene.sim.time+(e.duration||6);}
 function updateContinue(){const has=save.checkpoint&&!save.completed;$('continue').querySelector('span').textContent=has?'CONTINUE CAMPAIGN':save.completed?'REPLAY THE CRASH':'DEPLOY INTO CAMPAIGN';$('status').textContent=has?'CHECKPOINT SECURED':save.completed?'TRANSMISSION LOST':'AWAITING DEPLOYMENT';}
 function setMode(value){mode=value;document.body.dataset.phase=value;document.body.classList.toggle('playing',value!=='menu');$('menu').hidden=value!=='menu';$('hud').hidden=!['playing','paused'].includes(value);$('pause').hidden=value!=='paused';$('ending').hidden=!['dead','complete'].includes(value);clearInput();if(scene?.game?.canvas)scene.game.canvas.style.cursor=value==='playing'?'none':'default';}
 function start(training=false,retry=false,replay=false){if(!scene)return;scene.audio.unlock();scene.audio.stopAmbient();const cp=training?null:replay?null:save.completed?null:save.checkpoint;
  scene.sim=BPCore.create({training,checkpoint:cp,difficulty:settings.difficulty});if(!training&&!cp){save.checkpoint={stage:0,time:0,kills:0,damage:0,flows:0};save.completed=false;persist();}
  if(replay){save.completed=false;save.checkpoint={stage:0,time:0,kills:0,damage:0,flows:0};persist();}
  scene.renderer.build(scene.sim);scene.accumulator=0;padAngle=padTarget=scene.sim.player.angle||0;padAimIdle=0;padReach=PAD_REACH;scene.audio.startAmbient();$('training-equipment').hidden=!training;$('range-weapon').value='rifle';$('chapter').textContent=training?'LIVE FIRE / ALL EQUIPMENT':'ACT I / THE FALL';$('mission-title').textContent=training?'TRAINING RANGE':'THE CRASH';$('sector').textContent=training?'FIELD LAB / SECTOR 00':'VESPER CITY / SECTOR 07';$('radio').hidden=true;radioUntil=0;setMode('playing');$('status').textContent=training?'TRAINING ACTIVE':'ROOK / SIGNAL ACTIVE';scene.scale.refresh();scene.game.canvas.focus();lastHud=0;hud();drain();}
 function pause(){if(mode!=='playing')return;setMode('paused');scene.audio.pause();$('resume').focus();}
 function resume(){if(mode!=='paused')return;scene.audio.unlock();scene.audio.resume();scene.audio.startAmbient();setMode('playing');scene.accumulator=0;scene.game.canvas.focus();}
 function menu(){scene?.audio.stopAmbient();setMode('menu');updateContinue();$('continue').focus();}
 function end(e){if(e.type==='complete'){save.completed=true;const result={time:e.time,score:e.score,rating:e.rating};if(!save.best||result.score>save.best.score)save.best=result;for(const [k,v] of Object.entries(scene.sim.mastery))if(['rifle','pistol','shotgun'].includes(k))save.mastery[k]=(save.mastery[k]||0)+v;save.unlocks=Array.from(new Set([...save.unlocks,'shotgun','frag']));persist();setMode('complete');$('ending-eyebrow').textContent='CHAPTER ONE / COMPLETE';$('ending-title').innerHTML='NO ONE IS<br>COMING.';$('ending-copy').textContent='Your extraction burns over Vesper City. The missile came from your own side. Rook disappears into the tunnels with one question: who gave the order? The opening mission ends here. No Safe Ground is the next chapter in development.';$('ending-retry').textContent='REPLAY THE CRASH ↗';const s=scene.sim.stats;$('run-stats').innerHTML=`<span>FIELD RATING<b>${e.rating}</b></span><span>HOSTILES<b>${s.kills}</b></span><span>FLOW CHAINS<b>${s.flows}</b></span><span>TIME<b>${formatTime(e.time)}</b></span>`;
  }else{setMode('dead');$('ending-eyebrow').textContent='ROOK / SIGNAL LOST';$('ending-title').innerHTML='STAY IN<br>THE FIGHT.';$('ending-copy').textContent=scene.sim.training?'Live fire got the better of you. Reset the range and try a different approach.':'Your last checkpoint is secure. Use cover, watch attack telegraphs, and keep a stim for the extraction courtyard.';$('ending-retry').textContent=scene.sim.training?'RESET THE RANGE ↗':'RETRY CHECKPOINT ↗';$('run-stats').innerHTML=`<span>HOSTILES<b>${scene.sim.stats.kills}</b></span><span>TIME<b>${formatTime(scene.sim.time)}</b></span>`;}scene.audio.stopAmbient();$('ending-retry').focus();}
 function drain(){if(!scene?.sim)return;const events=scene.sim.events.splice(0);for(const e of events){scene.renderer.event(e);scene.audio.event(e);if(e.type==='radio')radio(e);if(e.type==='toast')toast(e.text);if(e.type==='flow')toast('PERFECT FLOW / MOMENTUM RETAINED',1.5);if(e.type==='checkpoint'&&!scene.sim.training){save.checkpoint=e.checkpoint;save.completed=false;persist();}if(e.type==='unlock'){save.unlocks=Array.from(new Set([...save.unlocks,...e.items]));persist();toast('M870 SHOTGUN + FRAG GRENADES ACQUIRED',4);}if(e.type==='pickup')toast(e.kind==='health'?'HEALTH RESTORED':e.kind==='armor'?'ARMOR REINFORCED':e.kind==='supply'?'FIELD EQUIPMENT RESTORED':'AMMUNITION RECOVERED',1.5);if(e.type==='death'||e.type==='complete')end(e);}}
 function formatTime(time){return Math.floor(time/60).toString().padStart(2,'0')+':'+Math.floor(time%60).toString().padStart(2,'0');}
 function minimap(s){const sx=148/s.map.width,sy=114/s.map.height,obj=s.map.objectives[Math.min(s.stage,s.map.objectives.length-1)];let svg='<svg viewBox="0 0 148 114" aria-label="Mission map">';for(const b of s.walls)if(!b.dead&&b.kind==='building')svg+=`<rect x="${b.x*sx}" y="${b.y*sy}" width="${b.w*sx}" height="${b.h*sy}" fill="#68755e" opacity=".55"/>`;for(const e of s.enemies)if(e.active&&!e.dead&&BPCore.distance(e,s.player)<1000)svg+=`<circle cx="${e.x*sx}" cy="${e.y*sy}" r="1.4" fill="#d18c72"/>`;if(!s.training)svg+=`<rect x="${obj.x*sx-2}" y="${obj.y*sy-2}" width="4" height="4" fill="none" stroke="#e2b074" stroke-width="1"/>`;svg+=`<circle cx="${s.player.x*sx}" cy="${s.player.y*sy}" r="2" fill="#e3e6c9"/></svg>`;return svg;}
 function hud(){const s=scene.sim,p=s.player,key=p.slots[p.slot],w=BPWorld.weapons[key],obj=s.map.objectives[Math.min(s.stage,s.map.objectives.length-1)];$('objective').textContent=obj.name;$('objective-hint').textContent=obj.hint;$('health-number').textContent=Math.ceil(p.health);$('health-bar').style.width=p.health+'%';$('health-bar').style.background=p.health<30?'#d18b70':'#d3ddbb';$('stamina-bar').style.width=p.stamina+'%';$('armor').textContent='ARMOR '+Math.ceil(p.armor);$('gadgets').textContent=`${keyLabel('gadget')} STIM ×${p.stims} / ${keyLabel('grenade')} FRAG ×${p.grenades}`;$('weapon-name').textContent=w.name;$('ammo').textContent=p.reload>0?'—':p.ammo[key].toString().padStart(2,'0');$('reserve').textContent=p.reload>0?' RELOADING':' / '+p.reserve[key];$('weapon-slots').textContent=p.slots.map((k,i)=>`${keyLabel('slot'+(i+1))} ${k.toUpperCase()}${p.unlocks.includes(k)?'':' [LOCKED]'}`).join(' · ');$('state-label').textContent=p.heal>0?'HEALING':p.reload>0?'RELOADING':p.state==='idle'?'READY':p.state.toUpperCase();$('elapsed').textContent=formatTime(s.time);$('flow').textContent=s.flowTime>0?'PERFECT FLOW':'';$('minimap').innerHTML=minimap(s);
  const nearby=s.training?s.pickups.find(o=>o.type==='supply'&&BPCore.distance(o,p)<100):BPCore.distance(obj,p)<90&&s.stage!==3?obj:null;const low=s.walls.some(b=>!b.dead&&b.low&&b.kind!=='underpass'&&BPCore.circleBox(p.x+Math.cos(p.angle)*48,p.y+Math.sin(p.angle)*48,35,b));$('interact-prompt').hidden=!nearby&&!low;$('interact-prompt').querySelector('kbd').textContent=keyLabel('interact');$('interact-prompt').querySelector('span').textContent=nearby?s.training?'RESUPPLY':'INTERACT':'VAULT LOW COVER';if(s.time>radioUntil)$('radio').hidden=true;if(performance.now()>toastUntil)$('toast').style.opacity='0';scene.audio.pressure(s.director.pressure);
 }
 function bindButton(list,label,value,listening,prompt,pick){const button=document.createElement('button');button.type='button';button.innerHTML=`<span>${label}</span><b>${listening?prompt:value}</b>`;button.classList.toggle('listening',listening);button.addEventListener('click',pick);list.append(button);return button;}
 function bindings(){const list=$('bindings'),padList=$('pad-bindings');list.replaceChildren();padList.replaceChildren();
  for(const [key,label] of Object.entries(labels))bindButton(list,label,displayKey(settings.bindings[key]),bindingTarget===key,'PRESS KEY',()=>{bindingTarget=key;padBindingTarget=null;bindings();}).dataset.action=key;
  for(const key of Object.keys(BPSave.padBindings))bindButton(padList,padActionLabel(key),BPGamepad.labels[settings.padBindings[key]],padBindingTarget===key,'PRESS BUTTON',()=>{padBindingTarget=key;bindingTarget=null;bindings();}).dataset.padAction=key;
  strip();}
 function showSettings(){if(mode==='playing')pause();for(const id of ['difficulty','volume','shake','quality'])$(id).value=settings[id];for(const id of ['music','flash','gamepad','aimAssist'])$(id).checked=settings[id];padStatus();bindings();$('settings').showModal();}
 function settingsChanged(){settings.difficulty=$('difficulty').value;settings.volume=Number($('volume').value);settings.shake=Number($('shake').value);settings.music=$('music').checked;settings.flash=$('flash').checked;settings.gamepad=$('gamepad').checked;settings.aimAssist=$('aimAssist').checked;settings.quality=$('quality').value;padStatus();if(scene){scene.settings=settings;if(scene.sim)scene.sim.difficulty=settings.difficulty;scene.audio.settings=settings;scene.audio.stopAmbient();if(mode==='playing')scene.audio.startAmbient();}persist();}
 $('continue').addEventListener('click',()=>start());$('training').addEventListener('click',()=>start(true));$('pause-button').addEventListener('click',pause);$('resume').addEventListener('click',resume);$('retry').addEventListener('click',()=>start(scene.sim.training,true));$('exit').addEventListener('click',menu);$('ending-menu').addEventListener('click',menu);$('ending-retry').addEventListener('click',()=>start(scene.sim.training,true,mode==='complete'));
 $('settings-button').addEventListener('click',showSettings);$('pause-settings').addEventListener('click',showSettings);$('settings').addEventListener('close',()=>{bindingTarget=padBindingTarget=null;settingsChanged();});$('settings').addEventListener('cancel',()=>{bindingTarget=padBindingTarget=null;});for(const id of ['difficulty','volume','shake','quality','music','flash','gamepad','aimAssist'])$(id).addEventListener('change',settingsChanged);
 $('reset-bindings').addEventListener('click',()=>{settings.bindings={...BPSave.bindings};settings.padBindings={...BPSave.padBindings};bindingTarget=padBindingTarget=null;bindings();persist();});$('sound').addEventListener('click',()=>{settings.muted=!settings.muted;$('sound').textContent=settings.muted?'SOUND OFF':'SOUND ON';persist();if(scene){scene.audio.unlock();scene.audio.stopAmbient();if(mode==='playing')scene.audio.startAmbient();}});$('sound').textContent=settings.muted?'SOUND OFF':'SOUND ON';
 for(const [key,w] of Object.entries(BPWorld.weapons)){const opt=document.createElement('option');opt.value=key;opt.textContent=w.name;$('range-weapon').append(opt);}$('range-weapon').addEventListener('change',()=>{if(!scene.sim.training)return;const key=$('range-weapon').value;scene.sim.player.slots[0]=key;scene.sim.player.slot=0;scene.sim.player.reload=0;hud();});
 window.addEventListener('keydown',e=>{if(padActive)setPadActive(false);if(padBindingTarget&&e.code==='Escape'){e.preventDefault();padBindingTarget=null;bindings();return;}if(bindingTarget){e.preventDefault();if(e.code==='Escape'){bindingTarget=null;bindings();return;}if(!e.repeat){const old=settings.bindings[bindingTarget],other=Object.keys(settings.bindings).find(k=>settings.bindings[k]===e.code);if(other)settings.bindings[other]=old;settings.bindings[bindingTarget]=e.code;bindingTarget=null;bindings();persist();}return;}if($('settings').open)return;if(e.code==='Escape'){e.preventDefault();if(mode==='playing')pause();else if(mode==='paused')resume();return;}if(mode!=='playing')return;if(Object.values(settings.bindings).includes(e.code)){e.preventDefault();if(!held.has(e.code))pressed.add(e.code);held.add(e.code);}}, {passive:false});
 window.addEventListener('keyup',e=>held.delete(e.code));window.addEventListener('blur',()=>{clearInput();pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();pause();}});window.addEventListener('pagehide',()=>{if(scene){scene.audio.destroy();scene.game.destroy(true);}});
 window.addEventListener('pointermove',e=>{if(padActive&&Math.hypot(e.movementX,e.movementY)>3)setPadActive(false);});window.addEventListener('pointerdown',()=>{if(padActive)setPadActive(false);});
 window.addEventListener('gamepadconnected',()=>{padStatus();if(settings.gamepad&&mode==='playing')toast('CONTROLLER CONNECTED');});window.addEventListener('gamepaddisconnected',()=>{padStatus();if(padActive&&mode==='playing')pause();});
 function padMenu(state){const root=$(mode==='menu'?'menu':mode==='paused'?'pause':'ending'),buttons=[...root.querySelectorAll('button')].filter(b=>b.offsetParent!==null),at=buttons.indexOf(document.activeElement),flick=Math.abs(state.move.y)>.6?Math.sign(state.move.y):0;
  let dir=Number(state.tap.has('down')||state.tap.has('right'))-Number(state.tap.has('up')||state.tap.has('left'));if(flick!==padMenuStick){padMenuStick=flick;dir=dir||flick;}
  if(at<0){if(dir||state.tap.has('a'))buttons[0]?.focus();return;}
  if(dir)buttons[(at+dir+buttons.length)%buttons.length].focus();if(state.tap.has('a'))buttons[at].click();else if(state.tap.has('b')&&mode==='paused')resume();}
 function pollPad(dt){const state=settings.gamepad?pad.poll():null;if(!state){padState=null;if(padActive)setPadActive(false);return;}
  if(state.active&&!padActive)setPadActive(true);
  if($('settings').open){const name=[...state.tap].find(n=>n!=='start');
   if(!padBindingTarget){if(state.tap.has('b')||state.tap.has('start'))$('settings').close();}
   else if(state.tap.has('start')){padBindingTarget=null;bindings();}
   else if(name){const b=settings.padBindings,other=Object.keys(b).find(k=>b[k]===name);if(other)b[other]=b[padBindingTarget];b[padBindingTarget]=name;padBindingTarget=null;bindings();persist();}
   return;}
  if(state.tap.has('start')&&mode==='playing'){pause();return;}if(state.tap.has('start')&&mode==='paused'){resume();return;}
  if(mode!=='playing'){padMenu(state);return;}
  padState=state;const pb=settings.padBindings,p=scene.sim.player,aimHeld=state.down.has(pb.aim),stick=state.aim.len?Math.atan2(state.aim.y,state.aim.x):null;for(const [action,name] of Object.entries(pb))if(state.tap.has(name))padTaps.add(action);
  // Aim assist: pressing steady aim locks onto the best target the gun is roughly facing; pulling the stick away switches target or releases.
  if(!aimHeld||!settings.aimAssist)padLock=null;else if(state.tap.has(pb.aim))padLock=assistTarget(padAngle);
  if(padLock){padLockLost=BPCore.lineOfSight(scene.sim,p,padLock)?0:padLockLost+dt;if(padLock.dead||padLockLost>.35)padLock=null;else if(stick!==null&&Math.abs(wrapAngle(stick-Math.atan2(padLock.y-p.y,padLock.x-p.x)))>ASSIST_BREAK)padLock=assistTarget(stick);}
  if(padLock){padTarget=Math.atan2(padLock.y-p.y,padLock.x-p.x);padAimIdle=0;}else if(stick!==null){padTarget=stick;padAimIdle=0;}else{padAimIdle+=dt;if(padAimIdle>.8&&state.move.len&&!state.down.has(pb.fire)&&!aimHeld)padTarget=Math.atan2(state.move.y,state.move.x);}
  padAngle+=wrapAngle(padTarget-padAngle)*(1-Math.exp(-dt*(padLock?ASSIST_TURN:PAD_TURN)));padReach+=((padLock?Math.max(60,BPCore.distance(p,padLock)):PAD_REACH)-padReach)*(1-Math.exp(-dt*18));}
 function wrapAngle(a){return Math.atan2(Math.sin(a),Math.cos(a));}
 function assistTarget(angle){const s=scene.sim,p=s.player,view=scene.cameras.main.worldView;let best=null,bestScore=Infinity;padLockLost=0;
  for(const e of s.enemies){if(e.dead||!view.contains(e.x,e.y)||!BPCore.lineOfSight(s,p,e))continue;const off=Math.abs(wrapAngle(Math.atan2(e.y-p.y,e.x-p.x)-angle)),score=off+BPCore.distance(p,e)/3000;if(off<ASSIST_CONE&&score<bestScore){best=e;bestScore=score;}}
  return best;}
 const padPointer={get x(){const cam=scene.cameras.main,p=scene.sim.player;return p.x+Math.cos(p.angle)*padReach-cam.midPoint.x+cam.width/2;},get y(){const cam=scene.cameras.main,p=scene.sim.player;return p.y+Math.sin(p.angle)*padReach-cam.midPoint.y+cam.height/2;}};
 function input(){const b=settings.bindings,pb=settings.padBindings,g=padState,down=key=>held.has(b[key])||!!g&&g.down.has(pb[key]),tap=key=>pressed.has(b[key])||padTaps.has(key);
  let mx=Number(down('right'))-Number(down('left')),my=Number(down('down'))-Number(down('up')),aimX,aimY;if(g&&g.move.len&&!mx&&!my){mx=g.move.x;my=g.move.y;}
  if(padActive){const p=scene.sim.player;aimX=p.x+Math.cos(padAngle)*padReach;aimY=p.y+Math.sin(padAngle)*padReach;}else{const pointer=scene.input.activePointer,world=scene.cameras.main.getWorldPoint(pointer.x,pointer.y);aimX=world.x;aimY=world.y;}
  return {mx,my,sprint:down('sprint'),roll:tap('roll'),slide:tap('slide'),interact:tap('interact'),reload:tap('reload'),gadget:tap('gadget'),melee:tap('melee'),meleeDown:down('melee'),grenade:tap('grenade'),fire:mouseFire||!!g&&g.down.has(pb.fire),aiming:mouseAim||!!g&&g.down.has(pb.aim),aimX,aimY,slot:tap('slot1')?0:tap('slot2')?1:tap('slot3')?2:undefined};}
 class FieldScene extends Phaser.Scene {
  constructor(){super('field');}
  preload(){this.load.on('progress',v=>{$('load-bar').style.width=Math.round(v*100)+'%';});this.load.on('loaderror',file=>{if(this.loadFailed)return;this.loadFailed=true;$('load-text').textContent=location.protocol==='file:'?'CANNOT RUN FROM A LOCAL FILE / RUN "NPM RUN SERVE" THEN OPEN HTTP://127.0.0.1:8127/BLACKOUT-PROTOCOL.HTML':'ASSET LOAD FAILED: '+file.key+' / REFRESH TO RETRY';});BPRender.preload(this);BPAudio.preload(this);}
  create(){scene=this;this.settings=settings;this.renderer=new BPRender(this);this.audio=new BPAudio(this,settings);this.accumulator=0;this.cameras.main.setZoom(1.03);this.game.canvas.tabIndex=0;this.game.canvas.setAttribute('aria-label','Top-down battlefield. Use WASD to move, mouse to aim, and left click to fire, or a controller: left stick to move, right stick to aim, right trigger to fire.');this.input.mouse.disableContextMenu();this.input.on('pointerdown',pointer=>{if(mode!=='playing')return;this.audio.unlock();if(pointer.button===0)mouseFire=true;if(pointer.button===2)mouseAim=true;});this.input.on('pointerup',pointer=>{if(pointer.button===0)mouseFire=false;if(pointer.button===2)mouseAim=false;});this.game.canvas.addEventListener('contextmenu',e=>e.preventDefault());window.addEventListener('pointerup',e=>{if(e.button===0)mouseFire=false;if(e.button===2)mouseAim=false;});if(!this.loadFailed)$('loading').hidden=true;updateContinue();document.body.dataset.phase='menu';
   const inspect=()=>({mode,camera:{scrollX:this.cameras.main.scrollX,scrollY:this.cameras.main.scrollY,zoom:this.cameras.main.zoom,width:this.cameras.main.width,height:this.cameras.main.height,originX:this.cameras.main.originX,originY:this.cameras.main.originY},world:JSON.parse(JSON.stringify({map:this.sim.map,walls:this.sim.walls,player:this.sim.player,enemies:this.sim.enemies,stage:this.sim.stage,time:this.sim.time,completed:this.sim.completed,dead:this.sim.dead,stats:this.sim.stats}))});
   window.BPApp={inspect,snapshot:()=>this.sim?{mode,training:this.sim.training,time:this.sim.time,stage:this.sim.stage,health:this.sim.player.health,armor:this.sim.player.armor,stamina:this.sim.player.stamina,x:this.sim.player.x,y:this.sim.player.y,state:this.sim.player.state,weapon:this.sim.player.slots[this.sim.player.slot],ammo:this.sim.player.ammo[this.sim.player.slots[this.sim.player.slot]],reload:this.sim.player.reload,stims:this.sim.player.stims,grenades:this.sim.player.grenades,kills:this.sim.stats.kills,flows:this.sim.stats.flows,activeEnemies:this.sim.enemies.filter(e=>!e.dead&&e.active).length,projectiles:this.sim.projectiles.filter(p=>p.active).length,particles:this.renderer.particles.filter(p=>p.active).length,audioUnlocked:this.audio.unlocked,audioContext:this.sound.context?.state,averageFps:this.game.loop.actualFps,save:JSON.parse(JSON.stringify(save))}:{mode}};
  }
  update(time,delta){const dt=Math.min(delta/1000,.05);pollPad(dt);if(mode!=='playing'||!this.sim)return;this.accumulator+=dt;let frameInput=input();let steps=0;while(this.accumulator>=BPCore.DT&&steps<7&&mode==='playing'){BPCore.step(this.sim,frameInput);this.accumulator-=BPCore.DT;steps++;pressed.clear();padTaps.clear();frameInput={...frameInput,roll:false,slide:false,interact:false,reload:false,gadget:false,melee:false,grenade:false,slot:undefined};}drain();this.renderer.update(this.sim,dt,padActive?padPointer:this.input.activePointer);if(time-lastHud>70){lastHud=time;hud();}}
 }
 function renderType(){const choice=new URLSearchParams(location.search).get('renderer');if(choice==='canvas')return Phaser.CANVAS;if(choice==='webgl')return Phaser.WEBGL;
  try{const testCanvas=document.createElement('canvas'),gl=testCanvas.getContext('webgl',{failIfMajorPerformanceCaveat:true});if(!gl)return Phaser.CANVAS;const ext=gl.getExtension('WEBGL_debug_renderer_info'),name=ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):'';const software=/swiftshader|llvmpipe|software/i.test(name);gl.getExtension('WEBGL_lose_context')?.loseContext();return software?Phaser.CANVAS:Phaser.AUTO;}catch{return Phaser.CANVAS;}}
 try{new Phaser.Game({type:renderType(),parent:'game',backgroundColor:'#252d24',scene:FieldScene,scale:{mode:Phaser.Scale.RESIZE,width:window.innerWidth,height:window.innerHeight},render:{antialias:true,pixelArt:false,roundPixels:false,powerPreference:'high-performance'},fps:{target:60,forceSetTimeOut:false},audio:{disableWebAudio:false},input:{keyboard:false}});}catch(err){$('load-text').textContent='COULD NOT INITIALIZE THE GAME. PLEASE REFRESH.';console.error(err);}
})();
