(() => {
 'use strict';
 let storage;try{storage=window.localStorage;}catch{storage=null;}
 const $=id=>document.getElementById(id),save=BPSave.load(storage),settings=save.settings,pressed=new Set(),held=new Set();
 const W=BPWorld.weapons,G=BPWorld.gear,A=BPWorld.archetypes,U=BPWorld.upgrades,MISSIONS=BPWorld.missions,DIFFS=BPWorld.order,DL=BPWorld.difficulties,Meta=BPMeta;
 const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced){settings.shake=0;settings.flash=true;}
 let scene=null,mode='menu',bindingTarget=null,lastHud=0,radioUntil=0,toastUntil=0,bannerUntil=0,comboUntil=0,mouseFire=false,mouseAim=false,wheelSwap=false,hadSaveFailure=false,selected=null,armoryTab='weapons',armoryItem=null,armoryFrom='menu',run=null,timeScale=1,slowUntil=0,debriefTimers=[];
 const labels={up:'Move up',down:'Move down',left:'Move left',right:'Move right',sprint:'Sprint',roll:'Roll / dive',slide:'Slide',interact:'Interact / vault',reload:'Reload',swap:'Swap weapon',gadget:'Stim injector',melee:'Melee',grenade:'Lethal gadget',tactical:'Tactical gadget',slot1:'Primary weapon',slot2:'Secondary weapon'};
 const pad=new BPGamepad(),padTaps=new Set(),PAD_REACH=300,PAD_TURN=14,ASSIST_TURN=45,ASSIST_CONE=.7,ASSIST_BREAK=.6,padActionLabel=key=>labels[key]||{fire:'Fire',aim:'Steady aim'}[key];
 let padState=null,padActive=false,padAngle=0,padTarget=0,padAimIdle=0,padMenuStick=0,padBindingTarget=null,padLock=null,padLockLost=0,padReach=PAD_REACH;
 const today=()=>Math.floor((Date.now()-new Date().getTimezoneOffset()*60000)/86400000),fmt=n=>Math.round(n).toLocaleString('en-US'),esc=t=>String(t).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
 const missionMeta=id=>MISSIONS.find(m=>m.id===id),gearName=k=>k?G[k].name:'NONE';
 function displayKey(code){return code.replace(/^Key|^Digit/,'').replace('Left','').replace('Right','');}
 function keyLabel(action){return padActive?BPGamepad.labels[settings.padBindings[action]]||'—':displayKey(settings.bindings[action]||'');}
 function strip(){$('controls-strip').textContent=`${keyLabel('sprint')} SPRINT / ${keyLabel('slide')} SLIDE / ${keyLabel('roll')} ROLL / ${keyLabel('interact')} VAULT / ${keyLabel('swap')} SWAP / ${keyLabel('reload')} RELOAD / ${keyLabel('melee')} MELEE / ${padActive?'START':'ESC'} PAUSE`;}
 function setPadActive(value){padActive=value;document.body.classList.toggle('pad',value);if(value&&scene?.sim)padAngle=padTarget=scene.sim.player.angle;padAimIdle=0;strip();}
 function padStatus(){const name=settings.gamepad?pad.name:null;$('gamepad-status').textContent=!BPGamepad.supported?'NOT SUPPORTED IN THIS BROWSER':!settings.gamepad?'OFF':name?name.slice(0,34):'PRESS ANY BUTTON ON THE CONTROLLER';}
 function persist(){const ok=BPSave.write(storage,save);if(!ok&&!hadSaveFailure){hadSaveFailure=true;toast('STORAGE UNAVAILABLE / PROGRESS LASTS THIS SESSION');}return ok;}
 function clearInput(){held.clear();pressed.clear();padTaps.clear();padState=null;padLock=null;mouseFire=false;mouseAim=false;wheelSwap=false;}
 function toast(text,duration=2.5){$('toast').textContent=text;$('toast').style.opacity='1';toastUntil=performance.now()+duration*1000;}
 function banner(eyebrow,title,sub='',duration=2.6,tone=''){$('banner-eyebrow').textContent=eyebrow;$('banner-title').textContent=title;$('banner-sub').textContent=sub;const b=$('banner');b.className='banner show '+tone;bannerUntil=performance.now()+duration*1000;}
 function radio(e){$('radio-speaker').textContent=e.speaker;$('radio-text').textContent=e.text;$('radio').hidden=false;radioUntil=scene.sim.time+(e.duration||6);}
 const rank=()=>Meta.rankOf(save.xp);
 function refreshWallet(){const r=rank();for(const id of ['wallet','ops-credits','armory-credits'])$(id).textContent=fmt(save.credits)+' CR';for(const id of ['ops-rank','armory-rank'])$(id).textContent='RANK '+r.rank+' · '+r.title;
  $('rank-chip').innerHTML=`<i></i> RANK ${r.rank} · ${esc(r.title)}`;const d=save.daily,day=today();$('streak-chip').textContent=d.day===day?`DAILY OP DONE · STREAK ${d.streak}`:d.day===day-1?`DAILY OP READY · KEEP THE ${d.streak}-DAY STREAK`:'DAILY OP BONUS READY';
  const fresh=[...save.owned.weapons,...save.owned.gear].filter(k=>!save.seen.includes(k)&&!['rifle','pistol'].includes(k)).length;$('armory-badge').textContent=fresh?'NEW ×'+fresh:fmt(save.credits)+' CR';$('armory-badge').classList.toggle('new',!!fresh);}
 function updateContinue(){const next=Meta.nextMission(save),cur=save.run&&missionMeta(save.run.mission),done=MISSIONS.filter(m=>save.missions[m.id]?.done).length,medals=MISSIONS.reduce((n,m)=>n+(save.missions[m.id]?.medals.length||0),0);
  $('continue').querySelector('span').textContent=cur?'CONTINUE · '+cur.title:next?(done?'NEXT OPERATION · '+next.title:'DEPLOY INTO CAMPAIGN'):'CAMPAIGN / ALL OPERATIONS';
  $('status').textContent=cur?'CHECKPOINT SECURED':done===MISSIONS.length?'ACT II COMPLETE':done?'OPERATIONS '+done+' / '+MISSIONS.length:'AWAITING DEPLOYMENT';
  const show=cur||next||MISSIONS[MISSIONS.length-1];$('dossier-act').textContent=String(show.n).padStart(2,'0')+' / '+show.act.replace(' / ',' · ');$('dossier-title').textContent=show.title;$('dossier-copy').textContent=show.brief;$('dossier-chapter').textContent='CHAPTER '+['ONE','TWO','THREE','FOUR','FIVE','SIX'][show.n-1];$('dossier-sector').textContent=show.sector.replace(' / ',' · ');
  $('dossier-progress').textContent=done+' / '+MISSIONS.length;$('dossier-medals').textContent=medals+' / '+MISSIONS.length*5;$('dossier-status').textContent=cur?'CHECKPOINT SAVED':done===MISSIONS.length?'HUNTING VOSS':done?'ON THE RUN':'MISSING IN ACTION';$('dossier-n').textContent=String(show.n).padStart(2,'0')+' / '+String(MISSIONS.length).padStart(2,'0');
  const hold=!!save.missions.crash?.done,best=Math.max(0,...Object.values(save.holdout));$('holdout').innerHTML=hold?`HOLDOUT / ENDLESS WAVES <span>${best?'BEST WAVE '+best:'↗'}</span>`:'HOLDOUT <span>FINISH THE CRASH TO UNLOCK</span>';$('holdout').classList.toggle('locked',!hold);refreshWallet();}
 const SCREENS=['menu','ops','armory'];
 function setMode(value){mode=value;document.body.dataset.phase=value;const game=['playing','paused','dead','complete'].includes(value);document.body.classList.toggle('playing',game);for(const id of SCREENS)$(id).hidden=value!==id;$('hud').hidden=!['playing','paused'].includes(value);$('pause').hidden=value!=='paused';$('ending').hidden=!['dead','complete'].includes(value);if(!game){$('danger').style.opacity='0';$('flashout').style.opacity='0';}clearInput();if(scene?.game?.canvas)scene.game.canvas.style.cursor=value==='playing'?'none':'default';}
 // ---------- operations board ----------
 function openOps(id){if(!scene)return;selected=id||selected||save.run?.mission||Meta.nextMission(save)?.id||'crash';if(!Meta.unlocked(save,selected))selected=Meta.nextMission(save)?.id||'crash';scene.audio?.stopAmbient();setMode('ops');renderOps();$('deploy').focus();}
 function medalRow(id){const got=save.missions[id]?.medals||[];return Meta.medalsFor().map(m=>`<i class="${got.includes(m.id)?'on':''}" title="${m.name}"></i>`).join('');}
 function renderOps(){const list=$('mission-list');list.replaceChildren();
  for(const m of MISSIONS){const st=save.missions[m.id],open=Meta.unlocked(save,m.id),b=document.createElement('button');b.type='button';b.className='mission-card'+(m.id===selected?' active':'')+(open?'':' locked')+(st?.done?' done':'');b.dataset.mission=m.id;
   b.innerHTML=`<span class="mc-n">${String(m.n).padStart(2,'0')}</span><span class="mc-body"><b>${open?m.title:'CLASSIFIED'}</b><small>${open?m.act:'COMPLETE '+esc(MISSIONS[m.n-2]?.title||'')+' TO DECLASSIFY'}</small><span class="medals">${medalRow(m.id)}</span></span><span class="mc-tag">${save.run?.mission===m.id?'CHECKPOINT':st?.best?st.best.rating+' / '+DL[st.best.difficulty].label:open?'NEW':'🔒'}</span>`;
   b.addEventListener('click',()=>{selected=m.id;renderOps();});list.append(b);}
  const m=missionMeta(selected),st=save.missions[m.id],open=Meta.unlocked(save,m.id);
  $('brief-act').textContent=m.act+' / CHAPTER '+m.n;$('brief-title').textContent=open?m.title:'CLASSIFIED';$('brief-sector').textContent=m.sector;$('brief-copy').textContent=open?m.brief:'Finish the previous operation to declassify this file.';
  $('brief-terrain').textContent=m.terrain;$('brief-threats').textContent=m.threats.map(t=>A[t].name).join(' · ');$('brief-best').textContent=st?.best?`${st.best.rating} · ${fmt(st.best.score)} · ${DL[st.best.difficulty].label}`:'—';$('brief-medals').innerHTML=medalRow(m.id);
  const rec=$('brief-rec');rec.replaceChildren();const head=document.createElement('p');head.className='rec-note';head.innerHTML=`<b>RECOMMENDED</b> ${esc(m.rec.note)}`;rec.append(head);
  for(const [kind,key] of [...m.rec.weapons.map(k=>['weapon',k]),...m.rec.gear.map(k=>['gear',k])]){const item=kind==='weapon'?W[key]:G[key],have=Meta.owns(save,kind,key),slot=kind==='weapon'?(item.slot===0?'primary':'secondary'):item.slot,on=save.loadout[slot]===key,cost=Meta.price(save,kind,key),b=document.createElement('button');b.type='button';b.className='rec-item'+(have?' owned':'')+(on?' on':'');
   b.innerHTML=`<span>${esc(item.name)}</span><b>${on?'EQUIPPED':have?'EQUIP':save.credits>=cost?'BUY '+fmt(cost)+' CR':fmt(cost)+' CR'}</b>`;
   b.addEventListener('click',()=>{if(!have){const r=Meta.buy(save,kind,key);if(!r.ok){toast(r.reason);scene.audio.ui('deny');return;}scene.audio.ui('buy');toast(item.name+' PURCHASED');}save.loadout[slot]=key;save.loadout=Meta.loadout(save);persist();refreshWallet();renderOps();});rec.append(b);}
  const dp=$('difficulty-pick');dp.replaceChildren();for(const d of DIFFS){const b=document.createElement('button');b.type='button';b.className=(settings.difficulty===d?'active ':'')+d;b.innerHTML=`<span>${DL[d].label}</span><small>×${DL[d].reward} CR</small>`;b.addEventListener('click',()=>{settings.difficulty=d;persist();renderOps();});dp.append(b);}
  $('difficulty-note').textContent={story:'Forgiving fire and frequent medkits. For the story.',standard:'The intended fight. Cover matters; mistakes are survivable.',intense:'Faster, deadlier enemies that throw grenades at campers.',insane:'Skill tier. Twice the soldiers, three-round bursts that lead your movement, grenades for anyone who camps. Fight from cover or die.'}[settings.difficulty];
  const lo=Meta.loadout(save),box=$('loadout');box.replaceChildren();
  for(const [slot,label] of [['primary','PRIMARY'],['secondary','SECONDARY'],['lethal','LETHAL'],['tactical','TACTICAL']]){const key=lo[slot],b=document.createElement('button');b.type='button';b.className='slot';b.dataset.slot=slot;const w=slot==='primary'||slot==='secondary'?W[key]:null;
   b.innerHTML=`<small>${label}</small><b>${esc(w?w.short:gearName(key))}</b><span>${w?esc(w.name.split(' / ')[1]):key?'×'+(G[key].count+(save.upgrades.bandolier||0)):'EMPTY / CHOOSE'}</span>`;b.addEventListener('click',()=>openPicker(slot));box.append(b);}
  const resume=save.run?.mission===m.id;$('resume-run').hidden=!resume;if(resume)$('resume-run').innerHTML=`RESUME CHECKPOINT · ${esc(m.title)} <span>↗</span>`;$('deploy').querySelector('span').textContent=!open?'LOCKED':resume?'RESTART OPERATION':st?.done?'REPLAY OPERATION':'DEPLOY';$('deploy').disabled=!open;refreshWallet();}
 function openPicker(slot){const list=$('picker-list'),gun=slot==='primary'||slot==='secondary';list.replaceChildren();$('picker-eyebrow').textContent=slot.toUpperCase();$('picker-title').textContent=gun?'CHOOSE A WEAPON.':'CHOOSE A GADGET.';
  const keys=gun?Object.keys(W).filter(k=>W[k].slot===(slot==='primary'?0:1)):[null,...Object.keys(G).filter(k=>G[k].slot===slot)];
  for(const key of keys){const have=key===null||(gun?save.owned.weapons:save.owned.gear).includes(key),item=key&&(gun?W[key]:G[key]),b=document.createElement('button');b.type='button';b.className='pick'+(save.loadout[slot]===key?' on':'')+(have?'':' locked');
   const lvl=gun?Meta.masteryLevel(save.mastery[key]||0):0;b.innerHTML=key===null?'<b>NONE</b><span>Leave this slot empty.</span>':`<b>${esc(item.name)}${gun&&lvl?' <em>'+'★'.repeat(lvl)+'</em>':''}</b><span>${have?esc(item.desc):'LOCKED · '+(item.drop?'DROPPED BY '+esc(item.drop).toUpperCase()+' · ':'')+'ARMORY '+fmt(item.price)+' CR'}</span>`;
   b.addEventListener('click',()=>{if(!have){$('picker').close();openArmory(gun?'weapons':'gear',key,'ops');return;}save.loadout[slot]=key;save.loadout=Meta.loadout(save);persist();$('picker').close();renderOps();scene.audio.ui('select');});list.append(b);}
  $('picker').showModal();list.querySelector('.on,button')?.focus();}
 // ---------- armory ----------
 function openArmory(tab='weapons',item=null,from=mode==='ops'?'ops':mode==='complete'||mode==='dead'?'menu':'menu'){armoryTab=tab;armoryItem=item;armoryFrom=from;scene?.audio?.stopAmbient();setMode('armory');renderArmory();($('armory-list').querySelector('.active')||$('armory-list').querySelector('button'))?.focus();}
 function bars(w){const max={damage:240*1,rate:16,range:1900,mobility:1.1,capacity:75},dps=w.damage*w.pellets/w.rate;return [['DAMAGE',Math.min(1,w.damage*w.pellets/200)],['FIRE RATE',Math.min(1,(1/w.rate)/16)],['RANGE',w.range/max.range],['MOBILITY',(w.mobility-.6)/.5],['MAGAZINE',Math.min(1,w.capacity/max.capacity)],['DPS',Math.min(1,dps/420)]].map(([l,v])=>`<div class="bar"><span>${l}</span><i style="--v:${Math.max(.04,Math.min(1,v)).toFixed(2)}"></i></div>`).join('');}
 function renderArmory(){for(const b of $('armory-tabs').children)b.classList.toggle('active',b.dataset.tab===armoryTab);const list=$('armory-list'),detail=$('armory-detail');list.replaceChildren();refreshWallet();
  list.hidden=armoryTab==='record';detail.classList.toggle('wide',armoryTab==='record');if(armoryTab==='record'){renderRecord(detail);return;}
  const entries=armoryTab==='weapons'?Object.keys(W).sort((a,b)=>W[a].slot-W[b].slot||W[a].price-W[b].price).map(k=>['weapon',k]):armoryTab==='gear'?Object.keys(G).sort((a,b)=>G[a].slot.localeCompare(G[b].slot)||G[a].price-G[b].price).map(k=>['gear',k]):Object.keys(U).map(k=>['upgrade',k]);
  if(!armoryItem||!entries.some(e=>e[1]===armoryItem))armoryItem=entries[0][1];
  for(const [kind,key] of entries){const item=kind==='weapon'?W[key]:kind==='gear'?G[key]:U[key],have=Meta.owns(save,kind,key),lvl=kind==='upgrade'?save.upgrades[key]||0:0,cost=Meta.price(save,kind,key),fresh=have&&kind!=='upgrade'&&!save.seen.includes(key)&&!['rifle','pistol'].includes(key),b=document.createElement('button');b.type='button';b.className='armory-item'+(key===armoryItem?' active':'')+(have?' owned':'');b.dataset.item=key;
   const tag=kind==='upgrade'?(lvl>=3?'MAX':'LV '+lvl+' · '+fmt(cost)+' CR'):have?(Object.values(save.loadout).includes(key)?'EQUIPPED':'OWNED'):fmt(cost)+' CR';
   b.innerHTML=`<span class="ai-kind">${kind==='weapon'?(item.slot===0?'PRIMARY':'SECONDARY'):kind==='gear'?item.slot.toUpperCase():'UPGRADE'}</span><b>${esc(item.name)}</b><span class="ai-tag${fresh?' new':''}">${fresh?'NEW · ':''}${tag}</span>`;
   b.addEventListener('click',()=>{armoryItem=key;renderArmory();});b.addEventListener('focus',()=>{if(armoryItem!==key){armoryItem=key;renderDetail(kind,key);for(const x of list.children)x.classList.toggle('active',x===b);}});list.append(b);}
  renderDetail(entries.find(e=>e[1]===armoryItem)[0],armoryItem);}
 function renderDetail(kind,key){const detail=$('armory-detail'),item=kind==='weapon'?W[key]:kind==='gear'?G[key]:U[key],have=Meta.owns(save,kind,key),cost=Meta.price(save,kind,key);
  if(have&&kind!=='upgrade'&&!save.seen.includes(key)){save.seen.push(key);persist();}
  let body='',actions=[];
  if(kind==='weapon'){const kills=save.mastery[key]||0,lvl=Meta.masteryLevel(kills),next=Meta.MASTERY[lvl];const slot=item.slot===0?'primary':'secondary';
   body=`<p class="ad-kind">${item.slot===0?'PRIMARY':'SECONDARY'} · ${item.cls.toUpperCase()}${item.pierce?' · PIERCES '+item.pierce:''}${item.explosive?' · EXPLOSIVE':''}${item.breach?' · BREACHES COVER':''}</p><h3>${esc(item.name)}</h3><p>${esc(item.desc)}</p><div class="bars">${bars(item)}</div>
    <div class="mastery"><b>MASTERY ${'★'.repeat(lvl)}${'☆'.repeat(3-lvl)}</b><span>${kills} KILLS${next?' · '+(next-kills)+' TO '+Meta.MASTERY_PERKS[lvl].toUpperCase():' · MASTERED'}</span></div><p class="ad-source">${have?'IN YOUR ARMORY':item.drop?'FIELD DROP: '+esc(item.drop).toUpperCase()+' — KILL ONE AND WALK OVER THE GUN':'ARMORY ONLY'}</p>`;
   if(have)actions.push([save.loadout[slot]===key?'EQUIPPED AS '+slot.toUpperCase():'EQUIP AS '+slot.toUpperCase(),()=>{save.loadout[slot]=key;save.loadout=Meta.loadout(save);persist();renderArmory();scene.audio.ui('select');}]);}
  else if(kind==='gear'){body=`<p class="ad-kind">${item.slot.toUpperCase()} GADGET · ${item.count} CHARGES PER MISSION</p><h3>${esc(item.name)}</h3><p>${esc(item.desc)}</p><p class="ad-source">${have?'IN YOUR ARMORY':'ARMORY ONLY'} · ${item.slot==='lethal'?keyLabel('grenade'):keyLabel('tactical')} TO USE</p>`;
   if(have)actions.push([save.loadout[item.slot]===key?'EQUIPPED':'EQUIP',()=>{save.loadout[item.slot]=key;save.loadout=Meta.loadout(save);persist();renderArmory();scene.audio.ui('select');}]);}
  else{const lvl=save.upgrades[key]||0;body=`<p class="ad-kind">PERMANENT UPGRADE · LEVEL ${lvl} / 3</p><h3>${esc(item.name)}</h3><p>${esc(item.desc)}</p><div class="pips">${[0,1,2].map(i=>`<i class="${i<lvl?'on':''}"></i>`).join('')}</div>`;}
  if(!have&&cost!=null)actions.unshift([save.credits>=cost?`BUY · ${fmt(cost)} CR`:`${fmt(cost)} CR · NEED ${fmt(cost-save.credits)} MORE`,()=>{const r=Meta.buy(save,kind,key);if(!r.ok){toast(r.reason);scene.audio.ui('deny');return;}scene.audio.ui('buy');if(kind==='weapon'){save.loadout[item.slot===0?'primary':'secondary']=key;}else if(kind==='gear')save.loadout[item.slot]=key;save.loadout=Meta.loadout(save);if(kind!=='upgrade')save.seen.push(key);persist();renderArmory();banner('ARMORY',kind==='upgrade'?item.name+' LV '+save.upgrades[key]:item.name,kind==='upgrade'?'UPGRADE INSTALLED':'PURCHASED · EQUIPPED',2.2,'gold');}]);
  detail.innerHTML=body+'<div class="ad-actions"></div>';const box=detail.querySelector('.ad-actions');actions.forEach(([label,fn],i)=>{const b=document.createElement('button');b.type='button';b.className=i===0&&!have?'primary':'secondary';b.innerHTML=`<span>${label}</span>`;b.addEventListener('click',fn);box.append(b);});}
 function renderRecord(detail){const r=rank(),c=Meta.refreshContracts(save,today());persist();
  detail.innerHTML=`<p class="ad-kind">SERVICE RECORD / ROOK</p><h3>RANK ${r.rank} · ${esc(r.title)}</h3><div class="xp-track big"><i style="width:${(r.into/r.span*100).toFixed(1)}%"></i></div><p>${fmt(r.into)} / ${fmt(r.span)} XP TO RANK ${r.rank+1} · EVERY RANK PAYS ${150*(r.rank+1)} CR</p>
   <h4>DAILY CONTRACTS <small>RESET AT MIDNIGHT</small></h4><div class="contracts">${c.map(x=>`<div class="contract${x.done?' done':''}"><span>${esc(x.text)}</span><i style="--v:${(x.progress/x.goal).toFixed(2)}"></i><b>${x.done?'PAID':x.progress+' / '+x.goal} · ${x.reward} CR</b></div>`).join('')}</div>
   <h4>RECORD</h4><div class="record"><span>HOSTILES <b>${fmt(save.stats.kills)}</b></span><span>OPERATIONS <b>${save.stats.missions}</b></span><span>DAILY STREAK <b>${save.daily.streak}</b></span><span>HOLDOUT BEST <b>${DIFFS.map(d=>save.holdout[d]?DL[d].label[0]+save.holdout[d]:'').filter(Boolean).join(' · ')||'—'}</b></span></div>
   <h4>MEDALS</h4><div class="medal-table">${MISSIONS.map(m=>`<span>${String(m.n).padStart(2,'0')} ${Meta.unlocked(save,m.id)?esc(m.title):'CLASSIFIED'}<b class="medals">${medalRow(m.id)}</b></span>`).join('')}</div>`;}
 // ---------- runs ----------
 function launch(o){if(!scene)return;scene.audio.unlock();scene.audio.stopAmbient();for(const t of debriefTimers)clearTimeout(t);debriefTimers=[];
  scene.sim=BPCore.create({training:o.mode==='training',mission:o.mission,difficulty:o.difficulty,checkpoint:o.checkpoint||null,loadout:o.loadout,owned:[...save.owned.weapons],profile:Meta.profile(save),seed:o.seed||1701});
  const meta=missionMeta(o.mission),training=o.mode==='training',hold=o.mode==='holdout';
  scene.renderer.build(scene.sim);scene.accumulator=0;padAngle=padTarget=scene.sim.player.angle||0;padAimIdle=0;padReach=PAD_REACH;timeScale=1;scene.audio.startAmbient(scene.sim.map.theme);
  $('training-equipment').hidden=!training;$('range-weapon').value='rifle';$('chapter').textContent=training?'LIVE FIRE / ALL EQUIPMENT':hold?'HOLDOUT / '+DL[o.difficulty].label:meta.act+' · '+DL[o.difficulty].label;$('mission-title').textContent=training?'TRAINING RANGE':hold?'KILLHOUSE':meta.title;$('sector').textContent=training?'FIELD LAB / SECTOR 00':hold?'SIMULATION / ENDLESS':meta.sector;
  $('pause-copy').textContent=training?'The range waits. Nothing here changes your campaign.':hold?'Waves resume when you do. Dying ends the run and banks its credits.':'Your checkpoint is secure. The city can wait.';$('retry').textContent=training?'RESET THE RANGE':hold?'RESTART HOLDOUT':'RETRY CHECKPOINT';
  $('radio').hidden=true;radioUntil=0;$('banner').className='banner';setMode('playing');$('status').textContent=training?'TRAINING ACTIVE':'ROOK / SIGNAL ACTIVE';scene.scale.refresh();scene.game.canvas.focus();lastHud=0;hud();drain();
  if(!training&&!hold&&!o.checkpoint?.stage)banner(meta.act,meta.title,meta.sector,3.4);if(hold)banner('HOLDOUT','KILLHOUSE','SURVIVE AS LONG AS YOU CAN',3);}
 function freshCheckpoint(){return {stage:0,time:0,kills:0,damage:0,flows:0,credits:0,intel:0,killed:[],dead:[]};}
 function startMission(id,resume=false){if(!Meta.unlocked(save,id))return;const lo=Meta.loadout(save);
  if(resume&&save.run?.mission===id){run={...save.run};launch({mode:'campaign',mission:id,difficulty:run.difficulty,checkpoint:run.checkpoint,loadout:lo});return;}
  run={mode:'campaign',mission:id,difficulty:settings.difficulty,floor:settings.difficulty,deaths:0};save.run={...run,checkpoint:freshCheckpoint()};persist();launch({mode:'campaign',mission:id,difficulty:run.difficulty,loadout:lo});}
 function startHoldout(){if(!save.missions.crash?.done){toast('FINISH THE CRASH TO UNLOCK HOLDOUT');return;}run={mode:'holdout',mission:'holdout',difficulty:settings.difficulty,floor:settings.difficulty,deaths:0};launch({mode:'holdout',mission:'holdout',difficulty:run.difficulty,loadout:Meta.loadout(save),seed:1701+Math.floor(Math.random()*1e6)});}
 function startTraining(){run={mode:'training',mission:'range',difficulty:settings.difficulty,floor:settings.difficulty,deaths:0};launch({mode:'training',mission:'range',difficulty:settings.difficulty});}
 function retry(){if(!run)return;if(run.mode==='training')startTraining();else if(run.mode==='holdout')startHoldout();else startMission(run.mission,!!save.run);}
 function pause(){if(mode!=='playing')return;setMode('paused');scene.audio.pause();$('resume').focus();}
 function resume(){if(mode!=='paused')return;scene.audio.unlock();scene.audio.resume();scene.audio.startAmbient(scene.sim.map.theme);setMode('playing');scene.accumulator=0;scene.game.canvas.focus();}
 function menu(){scene?.audio.stopAmbient();scene?.audio.vitals(100,false);for(const t of debriefTimers)clearTimeout(t);debriefTimers=[];setMode('menu');updateContinue();$('continue').focus();}
 function payDifficulty(){return DIFFS[Math.min(DIFFS.indexOf(run.difficulty),DIFFS.indexOf(run.floor||run.difficulty))];}
 function end(e){const s=scene.sim;scene.audio.stopAmbient();scene.audio.vitals(100,false);$('debrief').hidden=true;$('ending-next').hidden=true;$('ending-armory').hidden=run.mode==='training';
  if(e.type==='complete'&&run.mode==='campaign'){const meta=missionMeta(run.mission),summary=Meta.summarize(s,{rating:e.rating,score:e.score,deaths:run.deaths||0,difficulty:payDifficulty()}),report=Meta.settle(save,summary,today());save.run=null;persist();setMode('complete');
   $('ending-eyebrow').textContent='CHAPTER '+meta.n+' / '+meta.title+' / COMPLETE';$('ending-title').innerHTML=['NO ONE IS<br>COMING.','THE QUARTER<br>FALLS SILENT.','THE LOG<br>NAMES HIM.','UNDER THE<br>CORDON.','THE KEY<br>TURNS.','EVERY NAME<br>BURNS.'][meta.n-1];$('ending-copy').textContent=meta.outro;
   $('run-stats').innerHTML=`<span>FIELD RATING<b>${e.rating}</b></span><span>HOSTILES<b>${s.stats.kills}</b></span><span>BEST COMBO<b>×${s.stats.bestCombo}</b></span><span>TIME<b>${formatTime(e.time)}</b></span>`;
   const next=MISSIONS[meta.n];$('ending-next').hidden=!next;if(next)$('ending-next').innerHTML=`NEXT · ${esc(next.title)} <b>↗</b>`;$('ending-retry').textContent='REPLAY '+meta.title+' ↗';debrief(report);(next?$('ending-next'):$('ending-retry')).focus();return;}
  if(run.mode==='holdout'){const summary=Meta.summarize(s,{difficulty:payDifficulty()}),report=Meta.settle(save,summary,today());save.stats.deaths++;persist();setMode('dead');$('ending-eyebrow').textContent='HOLDOUT / '+DL[run.difficulty].label;$('ending-title').innerHTML=`WAVE ${s.stats.wave}<br>SURVIVED.`;$('ending-copy').textContent=report.newBest?'A new personal record. The killhouse resets — and so do you.':'Every wave you cleared paid out. Spend it, then come back for one more.';
   $('run-stats').innerHTML=`<span>WAVES<b>${s.stats.wave}</b></span><span>HOSTILES<b>${s.stats.kills}</b></span><span>BEST COMBO<b>×${s.stats.bestCombo}</b></span><span>TIME<b>${formatTime(s.time)}</b></span>`;$('ending-retry').textContent='GO AGAIN ↗';debrief(report);$('ending-retry').focus();return;}
  setMode('dead');if(run.mode==='campaign'){run.deaths=(run.deaths||0)+1;if(save.run)save.run.deaths=run.deaths;save.stats.deaths++;persist();}
  const meta=missionMeta(run.mission);$('ending-eyebrow').textContent='ROOK / SIGNAL LOST';$('ending-title').innerHTML='STAY IN<br>THE FIGHT.';
  $('ending-copy').textContent=s.training?'Live fire got the better of you. Reset the range and try a different approach.':(s.difficulty==='insane'?'Insane punishes open ground. Fight from corners, break line of sight when a telegraph lights up, and relocate before grenades land. ':'Your last checkpoint is secure. Watch attack telegraphs and use cover. ')+(meta?.rec?.note||'');
  $('ending-retry').textContent=s.training?'RESET THE RANGE ↗':'RETRY CHECKPOINT ↗';$('run-stats').innerHTML=`<span>HOSTILES<b>${s.stats.kills}</b></span><span>TIME<b>${formatTime(s.time)}</b></span>${run.mode==='campaign'?`<span>CREDITS AT RISK<b>${fmt(s.stats.credits)}</b></span>`:''}`;$('ending-retry').focus();}
 // The tally counts each line up with a tick, then fills the XP bar and calls out rank-ups, medals, mastery and contracts.
 function debrief(report){const box=$('debrief-lines'),awards=$('debrief-awards');box.replaceChildren();awards.replaceChildren();$('debrief').hidden=false;$('debrief-credits').textContent='0';const before=report.rankBefore,after=report.rankAfter||before;
  $('xp-rank').textContent='RANK '+before.rank+' · '+before.title;$('xp-fill').style.transition='none';$('xp-fill').style.width=(before.into/before.span*100)+'%';$('xp-note').textContent='+'+fmt(report.xp)+' XP';
  let total=0,t=350;const later=(fn,ms)=>debriefTimers.push(setTimeout(fn,ms));
  for(const l of report.lines){later(()=>{const row=document.createElement('div');row.className='dl';row.innerHTML=`<span>${esc(l.label)}${l.note?' <small>'+esc(l.note)+'</small>':''}</span><b>+0</b>`;box.append(row);const b=row.querySelector('b'),start=performance.now(),from=total;total+=l.value;const to=total;scene.audio.ui('tick');
    const step=()=>{const k=Math.min(1,(performance.now()-start)/320);b.textContent='+'+fmt(l.value*k);$('debrief-credits').textContent=fmt(from+(to-from)*k);if(k<1)requestAnimationFrame(step);};requestAnimationFrame(step);box.scrollTop=box.scrollHeight;},t);t+=Math.max(140,420-report.lines.length*18);}
  later(()=>{$('debrief-credits').textContent=fmt(report.credits);scene.audio.ui('total');$('xp-fill').style.transition='width .9s cubic-bezier(.2,.8,.2,1)';$('xp-fill').style.width=(after.rank>before.rank?100:after.into/after.span*100)+'%';refreshWallet();},t+200);
  const award=(cls,eyebrow,title,sub,sound)=>{const a=document.createElement('div');a.className='award '+cls;a.innerHTML=`<small>${esc(eyebrow)}</small><b>${esc(title)}</b><span>${esc(sub)}</span>`;awards.append(a);scene.audio.ui(sound);};
  t+=1150;for(const r of report.rankUps){later(()=>{$('xp-rank').textContent='RANK '+r.rank+' · '+r.title;$('xp-fill').style.transition='none';$('xp-fill').style.width='0%';requestAnimationFrame(()=>{$('xp-fill').style.transition='width .7s ease';$('xp-fill').style.width=(after.rank===r.rank?after.into/after.span*100:100)+'%';});award('gold','RANK UP','RANK '+r.rank+' · '+r.title,'+'+r.bonus+' CR','rank');},t);t+=700;}
  for(const m of report.medals){later(()=>award('medal','MEDAL',m.name,'+150 CR','medal'),t);t+=380;}
  for(const m of report.mastery){later(()=>award('mastery','WEAPON MASTERY',W[m.weapon].short+' '+'★'.repeat(m.level),m.perk.toUpperCase(),'medal'),t);t+=380;}
  for(const c of report.contracts.filter(c=>c.done)){later(()=>award('contract','CONTRACT',c.text,'PAID','medal'),t);t+=300;}
  if(report.newBest)later(()=>award('best','NEW PERSONAL BEST','RECORD','SAVED TO YOUR SERVICE RECORD','medal'),t);}
 function onEvent(e){const s=scene.sim;switch(e.type){
  case 'radio':radio(e);break;case 'toast':toast(e.text);break;case 'flow':toast('PERFECT FLOW / MOMENTUM RETAINED',1.5);break;
  case 'checkpoint':if(run?.mode==='campaign'){save.run={...run,checkpoint:e.checkpoint};persist();}break;
  case 'unlock':for(const k of e.items){if(W[k]&&!save.owned.weapons.includes(k))save.owned.weapons.push(k);if(G[k]&&!save.owned.gear.includes(k))save.owned.gear.push(k);}persist();banner('SUPPLY CACHE','M870 + FRAG GRENADES','SHOTGUN ON THE GROUND · '+keyLabel('interact')+' TO SWAP IT IN',4,'gold');break;
  case 'weaponfound':if(!save.owned.weapons.includes(e.weapon)){save.owned.weapons.push(e.weapon);persist();}banner('NEW WEAPON',W[e.weapon].name,'ADDED TO YOUR ARMORY · '+keyLabel('interact')+' TO EQUIP NOW',3.6,'gold');break;
  case 'pickup':if(e.kind!=='weapon')toast(e.kind==='health'?'HEALTH RESTORED':e.kind==='armor'?'ARMOR REINFORCED':e.kind==='supply'?'FIELD EQUIPMENT RESTORED':e.kind==='lethal'?'LETHAL RESUPPLIED':e.kind==='tactical'?'TACTICAL RESUPPLIED':e.kind==='intel'||e.kind==='cache'?'':'AMMUNITION RECOVERED',1.5);break;
  case 'intel':banner('CLASSIFIED','INTEL RECOVERED','+200 CR ON COMPLETION · MEDAL',3,'gold');break;case 'cache':toast('CREDIT CACHE / +120 CR',2);break;
  case 'objective':banner(e.partial?'OBJECTIVE':'OBJECTIVE COMPLETE',e.partial?e.name:e.name.toUpperCase(),'',2.4);break;
  case 'stage':if(e.stage>0){const st=s.map.stages[e.stage];setTimeout(()=>{if(mode==='playing')banner('NEW OBJECTIVE',st.name.toUpperCase(),st.hint,3);},2500);}break;
  case 'kill':comboUntil=performance.now()+3500;if(e.combo>=2){const name={2:'DOUBLE KILL',3:'TRIPLE KILL',5:'RAMPAGE',8:'UNSTOPPABLE',12:'BLACKOUT'}[e.combo];if(name)banner('×'+e.combo+' COMBO',name,'',1.4,'combo');}
   if(e.boss){slowUntil=performance.now()+1100;banner('TARGET DOWN',A[e.enemy].name+' DESTROYED','',3,'gold');}break;
  case 'waveclear':banner('WAVE '+e.wave+' CLEARED','+'+e.bonus+' CR','SUPPLIES RESTOCKED',2.6,'gold');slowUntil=performance.now()+700;break;
  case 'wave':banner('HOLDOUT','WAVE '+e.wave,e.wave%5===0?'COMMANDER INBOUND':'',2,e.wave%5===0?'danger':'');break;
  case 'armorbreak':toast('ARMOR BROKEN',1.4);break;case 'bossphase':toast('THE '+A[s.enemies.find(x=>x.id===e.id)?.type||'commander'].name+' IS ADAPTING',2);break;
  case 'flash':if(e.self&&!settings.flash){$('flashout').style.transition='none';$('flashout').style.opacity='.85';requestAnimationFrame(()=>{$('flashout').style.transition='opacity 1.3s ease-out';$('flashout').style.opacity='0';});}break;
  case 'death':case 'complete':end(e);break;}}
 function drain(){if(!scene?.sim)return;const events=scene.sim.events.splice(0);for(const e of events){scene.renderer.event(e);scene.audio.event(e);onEvent(e);if(mode!=='playing'&&(e.type==='death'||e.type==='complete'))break;}}
 function formatTime(time){return Math.floor(time/60).toString().padStart(2,'0')+':'+Math.floor(time%60).toString().padStart(2,'0');}
 function minimap(s){const sx=148/s.map.width,sy=114/s.map.height;let svg='<svg viewBox="0 0 148 114" aria-label="Mission map">';for(const b of s.walls)if(!b.dead&&(b.kind==='building'||b.kind==='rock'))svg+=`<rect x="${b.x*sx}" y="${b.y*sy}" width="${b.w*sx}" height="${b.h*sy}" fill="${b.kind==='rock'?'#4f5a4c':'#68755e'}" opacity=".55"/>`;else if(!b.dead&&b.kind==='gate')svg+=`<rect x="${b.x*sx}" y="${b.y*sy}" width="${Math.max(1.5,b.w*sx)}" height="${Math.max(1.5,b.h*sy)}" fill="#d18c72"/>`;
  for(const e of s.enemies)if(e.active&&!e.dead&&!(e.gone>0)&&BPCore.distance(e,s.player)<1000)svg+=`<circle cx="${e.x*sx}" cy="${e.y*sy}" r="${A[e.type].boss?2.6:1.4}" fill="#d18c72"/>`;if(!s.training&&s.mission!=='holdout')svg+=`<rect x="${s.goal.x*sx-2}" y="${s.goal.y*sy-2}" width="4" height="4" fill="none" stroke="#e2b074" stroke-width="1"/>`;svg+=`<circle cx="${s.player.x*sx}" cy="${s.player.y*sy}" r="2" fill="#e3e6c9"/></svg>`;return svg;}
 // What X / E would do right now. Controller X reloads when this is empty.
 function context(){const s=scene.sim,p=s.player,st=BPCore.stageDef(s);if(!s.training&&['clear','extract'].includes(st.kind)&&BPCore.distance(st,p)<90)return {kind:'interact',label:st.kind==='extract'?'EXTRACT':'INTERACT'};const gun=BPCore.nearbyWeapon(s);if(gun)return {kind:'weapon',label:'SWAP FOR '+W[gun.weapon].short};
  if(s.training&&s.pickups.some(o=>o.type==='supply'&&BPCore.distance(o,p)<100))return {kind:'interact',label:'RESUPPLY'};if(s.walls.some(b=>!b.dead&&b.low&&b.kind!=='underpass'&&BPCore.circleBox(p.x+Math.cos(p.angle)*48,p.y+Math.sin(p.angle)*48,35,b)||!b.dead&&b.low&&b.kind!=='underpass'&&BPCore.circleBox(p.x+p.vx*.2,p.y+p.vy*.2,35,b)))return {kind:'vault',label:'VAULT LOW COVER'};return null;}
 function hud(){const s=scene.sim,p=s.player,key=p.slots[p.slot],w=W[key],st=BPCore.stageDef(s),now=performance.now();$('objective').textContent=st.name;$('objective-hint').textContent=st.hint;
  const prog=st.kind==='destroy'||st.kind==='survive'||st.kind==='endless';$('objective-progress').hidden=!prog;if(prog)$('objective-fill').style.width=(st.kind==='endless'?(s.director.phase==='rest'?100:0):s.progress*100)+'%';if(st.kind==='survive')$('objective-hint').textContent=`${Math.max(0,Math.ceil(st.time-s.director.clock))}s remaining · ${st.hint}`;if(st.kind==='endless')$('objective').textContent=s.director.wave?`Wave ${s.director.wave} · ${s.enemies.filter(e=>!e.dead).length+s.spawnWarnings.length+(s.director.queue?.length||0)} hostiles`:'Get ready';
  $('health-number').textContent=Math.ceil(p.health);$('health-bar').style.width=p.health+'%';$('health-bar').style.background=p.health<30?'#d18b70':'#d3ddbb';$('armor-bar').style.width=Math.min(100,p.armor/p.maxArmor*100)+'%';$('stamina-bar').style.width=p.stamina+'%';$('armor').textContent='ARMOR '+Math.ceil(p.armor);
  $('gadgets').textContent=`${keyLabel('gadget')} STIM ×${p.stims} / ${keyLabel('grenade')} ${p.lethal?G[p.lethal].name.split(' ').pop()+' ×'+p.grenades:'—'} / ${keyLabel('tactical')} ${p.tactical?G[p.tactical].name.split(' ').pop()+' ×'+p.tacticals:'—'}`;
  $('weapon-name').textContent=w.name;$('ammo').textContent=p.reload>0?'—':p.ammo[key].toString().padStart(2,'0');$('ammo').classList.toggle('low',p.reload<=0&&p.ammo[key]<=Math.max(1,w.capacity*.2));$('reserve').textContent=p.reload>0?' RELOADING':' / '+p.reserve[key];
  $('weapon-slots').innerHTML=p.slots.map((k,i)=>`<em class="${i===p.slot?'on':''}">${esc(keyLabel('slot'+(i+1)))} ${esc(W[k].short)}</em>`).join(' <span>·</span> ')+` <span>·</span> ${esc(keyLabel('swap'))} SWAP`;
  $('state-label').textContent=p.heal>0?'HEALING':p.reload>0?'RELOADING':p.state==='idle'?'READY':p.state.toUpperCase();$('elapsed').textContent=formatTime(s.time);$('flow').textContent=s.flowTime>0?'PERFECT FLOW':'';$('minimap').innerHTML=minimap(s);
  $('run-credits').textContent=s.training?'RANGE':fmt(s.stats.credits)+' CR';const combo=now<comboUntil&&s.combo>=2;$('combo-mult').textContent=combo?'×'+s.combo+' COMBO':'';$('combo').classList.toggle('hot',combo);
  const boss=s.boss&&s.enemies.find(e=>e.id===s.boss);$('boss').hidden=!boss;if(boss){const t=A[boss.type];$('boss-name').textContent=t.name;$('boss-fill').style.width=Math.max(0,boss.hp/boss.maxHp*100)+'%';$('boss-note').textContent=t.barrier?(boss.barrierOff?'BARRIER DESTROYED':boss.shieldDown>0?'BARRIER DOWN · '+Math.ceil(boss.shieldDown)+'s':'BARRIER UP · BREAK A GENERATOR OR EMP IT'):t.armor?(boss.disabled>0?'SYSTEMS DOWN · FULL DAMAGE':'HEAVY ARMOUR · EXPLOSIVES'):t.blink?'RELOCATES AFTER EVERY SHOT':'';}
  const c=context();$('interact-prompt').hidden=!c;if(c){$('interact-prompt').querySelector('kbd').textContent=keyLabel('interact');$('interact-prompt').querySelector('span').textContent=c.label;}
  if(s.time>radioUntil)$('radio').hidden=true;if(now>toastUntil)$('toast').style.opacity='0';if(now>bannerUntil)$('banner').classList.remove('show');scene.audio.pressure(s.director.pressure);
  const hurt=mode==='playing'&&p.health<35&&!s.dead?1-p.health/35:0,el=$('danger');el.style.opacity=hurt?(.35+.6*hurt).toFixed(2):p.heal>0?'0':'0';el.classList.toggle('pulse',!!hurt&&!settings.flash);el.style.setProperty('--beat',(.45+.7*(p.health/35)).toFixed(2)+'s');document.body.classList.toggle('healing',p.heal>0);scene.audio.vitals(p.health,mode==='playing'&&!s.dead);
 }
 function bindButton(list,label,value,listening,prompt,pick){const button=document.createElement('button');button.type='button';button.innerHTML=`<span>${label}</span><b>${listening?prompt:value}</b>`;button.classList.toggle('listening',listening);button.addEventListener('click',pick);list.append(button);return button;}
 function bindings(){const list=$('bindings'),padList=$('pad-bindings');list.replaceChildren();padList.replaceChildren();
  for(const [key,label] of Object.entries(labels))bindButton(list,label,displayKey(settings.bindings[key]),bindingTarget===key,'PRESS KEY',()=>{bindingTarget=key;padBindingTarget=null;bindings();}).dataset.action=key;
  for(const key of Object.keys(BPSave.padBindings))bindButton(padList,padActionLabel(key),BPGamepad.labels[settings.padBindings[key]],padBindingTarget===key,'PRESS BUTTON',()=>{padBindingTarget=key;bindingTarget=null;bindings();}).dataset.padAction=key;
  strip();}
 function showSettings(){if(mode==='playing')pause();for(const id of ['difficulty','volume','shake','quality'])$(id).value=settings[id];for(const id of ['music','flash','gamepad','aimAssist'])$(id).checked=settings[id];padStatus();bindings();$('settings').showModal();}
 function settingsChanged(){settings.difficulty=$('difficulty').value;settings.volume=Number($('volume').value);settings.shake=Number($('shake').value);settings.music=$('music').checked;settings.flash=$('flash').checked;settings.gamepad=$('gamepad').checked;settings.aimAssist=$('aimAssist').checked;settings.quality=$('quality').value;padStatus();
  if(scene){scene.settings=settings;if(scene.sim&&['playing','paused'].includes(mode)&&run){scene.sim.difficulty=settings.difficulty;if(DIFFS.indexOf(settings.difficulty)<DIFFS.indexOf(run.floor||run.difficulty))run.floor=settings.difficulty;if(save.run&&run.mode==='campaign')save.run.floor=run.floor;}scene.audio.settings=settings;scene.audio.stopAmbient();if(mode==='playing')scene.audio.startAmbient(scene.sim.map.theme);}if(mode==='ops')renderOps();persist();}
 $('continue').addEventListener('click',()=>openOps());$('training').addEventListener('click',startTraining);$('holdout').addEventListener('click',startHoldout);$('armory-button').addEventListener('click',()=>openArmory('weapons',null,'menu'));
 $('deploy').addEventListener('click',()=>startMission(selected,false));$('resume-run').addEventListener('click',()=>startMission(selected,true));$('ops-armory').addEventListener('click',()=>openArmory('weapons',null,'ops'));$('ops-back').addEventListener('click',menu);
 $('armory-back').addEventListener('click',()=>armoryFrom==='ops'?openOps(selected):menu());for(const b of $('armory-tabs').children)b.addEventListener('click',()=>{armoryTab=b.dataset.tab;armoryItem=null;renderArmory();});
 $('picker-close').addEventListener('click',()=>$('picker').close());
 $('pause-button').addEventListener('click',pause);$('resume').addEventListener('click',resume);$('retry').addEventListener('click',retry);$('exit').addEventListener('click',menu);$('ending-menu').addEventListener('click',menu);$('ending-retry').addEventListener('click',()=>{if(mode==='complete'&&run.mode==='campaign'){startMission(run.mission,false);}else retry();});
 $('ending-next').addEventListener('click',()=>{const meta=missionMeta(run.mission),next=MISSIONS[meta.n];if(next)openOps(next.id);});$('ending-armory').addEventListener('click',()=>openArmory('weapons',null,'menu'));
 $('settings-button').addEventListener('click',showSettings);$('pause-settings').addEventListener('click',showSettings);$('settings').addEventListener('close',()=>{bindingTarget=padBindingTarget=null;settingsChanged();});$('settings').addEventListener('cancel',()=>{bindingTarget=padBindingTarget=null;});for(const id of ['difficulty','volume','shake','quality','music','flash','gamepad','aimAssist'])$(id).addEventListener('change',settingsChanged);
 $('reset-bindings').addEventListener('click',()=>{settings.bindings={...BPSave.bindings};settings.padBindings={...BPSave.padBindings};bindingTarget=padBindingTarget=null;bindings();persist();});$('sound').addEventListener('click',()=>{settings.muted=!settings.muted;$('sound').textContent=settings.muted?'SOUND OFF':'SOUND ON';persist();if(scene){scene.audio.unlock();scene.audio.stopAmbient();if(mode==='playing')scene.audio.startAmbient(scene.sim.map.theme);}});$('sound').textContent=settings.muted?'SOUND OFF':'SOUND ON';
 const option=(sel,value,text)=>{const o=document.createElement('option');o.value=value;o.textContent=text;$(sel).append(o);};
 for(const [key,w] of Object.entries(W))option('range-weapon',key,w.name);for(const [key,g] of Object.entries(G))option(g.slot==='lethal'?'range-lethal':'range-tactical',key,g.name);
 $('range-weapon').addEventListener('change',()=>{if(!scene.sim?.training)return;const key=$('range-weapon').value,p=scene.sim.player;p.slots[W[key].slot]=key;p.slot=W[key].slot;p.reload=0;hud();});
 for(const kind of ['lethal','tactical'])$('range-'+kind).addEventListener('change',()=>{if(!scene.sim?.training)return;scene.sim.player[kind]=$('range-'+kind).value;hud();});
 window.addEventListener('keydown',e=>{if(padActive)setPadActive(false);if(padBindingTarget&&e.code==='Escape'){e.preventDefault();padBindingTarget=null;bindings();return;}if(bindingTarget){e.preventDefault();if(e.code==='Escape'){bindingTarget=null;bindings();return;}if(!e.repeat){const old=settings.bindings[bindingTarget],other=Object.keys(settings.bindings).find(k=>settings.bindings[k]===e.code);if(other)settings.bindings[other]=old;settings.bindings[bindingTarget]=e.code;bindingTarget=null;bindings();persist();}return;}if($('settings').open||$('picker').open)return;
  if(e.code==='Escape'){e.preventDefault();if(mode==='playing')pause();else if(mode==='paused')resume();else if(mode==='ops')menu();else if(mode==='armory')armoryFrom==='ops'?openOps(selected):menu();return;}if(mode!=='playing')return;if(Object.values(settings.bindings).includes(e.code)){e.preventDefault();if(!held.has(e.code))pressed.add(e.code);held.add(e.code);}}, {passive:false});
 window.addEventListener('keyup',e=>held.delete(e.code));window.addEventListener('blur',()=>{clearInput();pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();pause();}});window.addEventListener('pagehide',()=>{if(scene){scene.audio.destroy();scene.game.destroy(true);}});
 window.addEventListener('wheel',e=>{if(mode==='playing'&&Math.abs(e.deltaY)>4)wheelSwap=true;},{passive:true});
 window.addEventListener('pointermove',e=>{if(padActive&&Math.hypot(e.movementX,e.movementY)>3)setPadActive(false);});window.addEventListener('pointerdown',()=>{if(padActive)setPadActive(false);});
 window.addEventListener('gamepadconnected',()=>{padStatus();if(settings.gamepad&&mode==='playing')toast('CONTROLLER CONNECTED');});window.addEventListener('gamepaddisconnected',()=>{padStatus();if(padActive&&mode==='playing')pause();});
 function menuRoot(){return $('picker').open?$('picker'):$(mode==='paused'?'pause':['dead','complete'].includes(mode)?'ending':mode);}
 function padMenu(state){const root=menuRoot(),buttons=[...root.querySelectorAll('button')].filter(b=>b.offsetParent!==null&&!b.disabled),at=buttons.indexOf(document.activeElement),flick=Math.abs(state.move.y)>.6?Math.sign(state.move.y):0;
  let dir=Number(state.tap.has('down')||state.tap.has('right'))-Number(state.tap.has('up')||state.tap.has('left'));if(flick!==padMenuStick){padMenuStick=flick;dir=dir||flick;}
  if(mode==='armory'&&!$('picker').open&&(state.tap.has('lb')||state.tap.has('rb'))){const tabs=['weapons','gear','upgrades','record'];armoryTab=tabs[(tabs.indexOf(armoryTab)+(state.tap.has('rb')?1:3))%4];armoryItem=null;renderArmory();$('armory-list').querySelector('button')?.focus();return;}
  if(state.tap.has('b')){if($('picker').open)$('picker').close();else if(mode==='paused')resume();else if(mode==='ops')menu();else if(mode==='armory')armoryFrom==='ops'?openOps(selected):menu();return;}
  if(at<0){if(dir||state.tap.has('a'))buttons[0]?.focus();return;}
  if(dir){const nextBtn=buttons[(at+dir+buttons.length)%buttons.length];nextBtn.focus();nextBtn.scrollIntoView({block:'nearest'});}if(state.tap.has('a'))buttons[at].click();}
 function pollPad(dt){const state=settings.gamepad?pad.poll():null;if(!state){padState=null;if(padActive)setPadActive(false);return;}
  if(state.active&&!padActive)setPadActive(true);
  if($('settings').open){const name=[...state.tap].find(n=>n!=='start');
   if(!padBindingTarget){if(state.tap.has('b')||state.tap.has('start'))$('settings').close();}
   else if(state.tap.has('start')){padBindingTarget=null;bindings();}
   else if(name){const b=settings.padBindings,other=Object.keys(b).find(k=>b[k]===name);if(other)b[other]=b[padBindingTarget];b[padBindingTarget]=name;padBindingTarget=null;bindings();persist();}
   return;}
  if(state.tap.has('start')&&mode==='playing'){pause();return;}if(state.tap.has('start')&&mode==='paused'){resume();return;}
  if(mode!=='playing'){padMenu(state);return;}
  padState=state;const pb=settings.padBindings,p=scene.sim.player,aimHeld=state.down.has(pb.aim),stick=state.aim.len?Math.atan2(state.aim.y,state.aim.x):null;for(const [action,name] of Object.entries(pb))if(state.tap.has(name))padTaps.add(action);
  // Aim assist: pressing steady aim locks onto the best target the gun is roughly facing; pulling the stick away switches target or releases.
  if(!aimHeld||!settings.aimAssist)padLock=null;else if(state.tap.has(pb.aim))padLock=assistTarget(padAngle);
  if(padLock){padLockLost=BPCore.lineOfSight(scene.sim,p,padLock)?0:padLockLost+dt;if(padLock.dead||padLock.gone>0||padLockLost>.35)padLock=null;else if(stick!==null&&Math.abs(wrapAngle(stick-Math.atan2(padLock.y-p.y,padLock.x-p.x)))>ASSIST_BREAK)padLock=assistTarget(stick);}
  if(padLock){padTarget=Math.atan2(padLock.y-p.y,padLock.x-p.x);padAimIdle=0;}else if(stick!==null){padTarget=stick;padAimIdle=0;}else{padAimIdle+=dt;if(padAimIdle>.8&&state.move.len&&!state.down.has(pb.fire)&&!aimHeld)padTarget=Math.atan2(state.move.y,state.move.x);}
  padAngle+=wrapAngle(padTarget-padAngle)*(1-Math.exp(-dt*(padLock?ASSIST_TURN:PAD_TURN)));padReach+=((padLock?Math.max(60,BPCore.distance(p,padLock)):PAD_REACH)-padReach)*(1-Math.exp(-dt*18));}
 function wrapAngle(a){return Math.atan2(Math.sin(a),Math.cos(a));}
 function assistTarget(angle){const s=scene.sim,p=s.player,view=scene.cameras.main.worldView;let best=null,bestScore=Infinity;padLockLost=0;
  for(const e of s.enemies){if(e.dead||e.gone>0||!view.contains(e.x,e.y)||!BPCore.lineOfSight(s,p,e))continue;const off=Math.abs(wrapAngle(Math.atan2(e.y-p.y,e.x-p.x)-angle)),score=off+BPCore.distance(p,e)/3000;if(off<ASSIST_CONE&&score<bestScore){best=e;bestScore=score;}}
  return best;}
 const padPointer={get x(){const cam=scene.cameras.main,p=scene.sim.player;return p.x+Math.cos(p.angle)*padReach-cam.midPoint.x+cam.width/2;},get y(){const cam=scene.cameras.main,p=scene.sim.player;return p.y+Math.sin(p.angle)*padReach-cam.midPoint.y+cam.height/2;}};
 function input(){const b=settings.bindings,pb=settings.padBindings,g=padState,down=key=>held.has(b[key])||!!g&&g.down.has(pb[key]),tap=key=>pressed.has(b[key])||padTaps.has(key);
  let mx=Number(down('right'))-Number(down('left')),my=Number(down('down'))-Number(down('up')),aimX,aimY;if(g&&g.move.len&&!mx&&!my){mx=g.move.x;my=g.move.y;}
  if(padActive){const p=scene.sim.player;aimX=p.x+Math.cos(padAngle)*padReach;aimY=p.y+Math.sin(padAngle)*padReach;}else{const pointer=scene.input.activePointer,world=scene.cameras.main.getWorldPoint(pointer.x,pointer.y);aimX=world.x;aimY=world.y;}
  let interact=tap('interact'),reload=tap('reload');if(padTaps.has('interact')&&!pressed.has(b.interact)&&!context()){interact=false;reload=true;}
  const swap=tap('swap')||wheelSwap;wheelSwap=false;
  return {mx,my,sprint:down('sprint'),roll:tap('roll'),slide:tap('slide'),interact,reload,swap,gadget:tap('gadget'),melee:tap('melee'),meleeDown:down('melee'),grenade:tap('grenade'),tactical:tap('tactical'),fire:mouseFire||!!g&&g.down.has(pb.fire),aiming:mouseAim||!!g&&g.down.has(pb.aim),aimX,aimY,slot:tap('slot1')?0:tap('slot2')?1:undefined};}
 class FieldScene extends Phaser.Scene {
  constructor(){super('field');}
  preload(){this.load.on('progress',v=>{$('load-bar').style.width=Math.round(v*100)+'%';});this.load.on('loaderror',file=>{if(this.loadFailed)return;this.loadFailed=true;$('load-text').textContent=location.protocol==='file:'?'CANNOT RUN FROM A LOCAL FILE / RUN "NPM RUN SERVE" THEN OPEN HTTP://127.0.0.1:8127/BLACKOUT-PROTOCOL.HTML':'ASSET LOAD FAILED: '+file.key+' / REFRESH TO RETRY';});BPRender.preload(this);BPAudio.preload(this);}
  create(){scene=this;this.settings=settings;this.renderer=new BPRender(this);this.audio=new BPAudio(this,settings);this.accumulator=0;this.cameras.main.setZoom(1.03);this.game.canvas.tabIndex=0;this.game.canvas.setAttribute('aria-label','Top-down battlefield. Use WASD to move, mouse to aim, and left click to fire, or a controller: left stick to move, right stick to aim, right trigger to fire, Y to swap weapons.');this.input.mouse.disableContextMenu();this.input.on('pointerdown',pointer=>{if(mode!=='playing')return;this.audio.unlock();if(pointer.button===0)mouseFire=true;if(pointer.button===2)mouseAim=true;});this.input.on('pointerup',pointer=>{if(pointer.button===0)mouseFire=false;if(pointer.button===2)mouseAim=false;});this.game.canvas.addEventListener('contextmenu',e=>e.preventDefault());window.addEventListener('pointerup',e=>{if(e.button===0)mouseFire=false;if(e.button===2)mouseAim=false;});if(!this.loadFailed)$('loading').hidden=true;updateContinue();document.body.dataset.phase='menu';
   const inspect=()=>({mode,camera:{scrollX:this.cameras.main.scrollX,scrollY:this.cameras.main.scrollY,zoom:this.cameras.main.zoom,width:this.cameras.main.width,height:this.cameras.main.height,originX:this.cameras.main.originX,originY:this.cameras.main.originY},world:JSON.parse(JSON.stringify({map:this.sim.map,walls:this.sim.walls,player:this.sim.player,enemies:this.sim.enemies,stage:this.sim.stage,goal:this.sim.goal,time:this.sim.time,completed:this.sim.completed,dead:this.sim.dead,stats:this.sim.stats,hazards:this.sim.hazards,grenades:this.sim.grenades,pickups:this.sim.pickups,difficulty:this.sim.difficulty,spawnWarnings:this.sim.spawnWarnings,zones:this.sim.zones,director:this.sim.director,progress:this.sim.progress,mission:this.sim.mission,training:this.sim.training}))});
   if(new URLSearchParams(location.search).has('qa'))window.BPQA={sim:()=>this.sim,end:e=>end(e),settle:()=>Meta,save};
   window.BPApp={inspect,snapshot:()=>this.sim?{mode,training:this.sim.training,mission:this.sim.mission,time:this.sim.time,stage:this.sim.stage,health:this.sim.player.health,armor:this.sim.player.armor,stamina:this.sim.player.stamina,x:this.sim.player.x,y:this.sim.player.y,state:this.sim.player.state,weapon:this.sim.player.slots[this.sim.player.slot],slots:[...this.sim.player.slots],ammo:this.sim.player.ammo[this.sim.player.slots[this.sim.player.slot]],reload:this.sim.player.reload,stims:this.sim.player.stims,grenades:this.sim.player.grenades,tacticals:this.sim.player.tacticals,kills:this.sim.stats.kills,flows:this.sim.stats.flows,credits:this.sim.stats.credits,activeEnemies:this.sim.enemies.filter(e=>!e.dead&&e.active).length,projectiles:this.sim.projectiles.filter(p=>p.active).length,particles:this.renderer.particles.filter(p=>p.active).length,danger:Number($('danger').style.opacity||0),audioUnlocked:this.audio.unlocked,audioContext:this.sound.context?.state,averageFps:this.game.loop.actualFps,save:JSON.parse(JSON.stringify(save))}:{mode,save:JSON.parse(JSON.stringify(save))}};
  }
  update(time,delta){let dt=Math.min(delta/1000,.05);pollPad(dt);if(mode!=='playing'||!this.sim)return;const now=performance.now();timeScale+=((now<slowUntil?.32:1)-timeScale)*Math.min(1,dt*(now<slowUntil?14:5));dt*=timeScale;this.accumulator+=dt;let frameInput=input();let steps=0;while(this.accumulator>=BPCore.DT&&steps<7&&mode==='playing'){BPCore.step(this.sim,frameInput);this.accumulator-=BPCore.DT;steps++;pressed.clear();padTaps.clear();frameInput={...frameInput,roll:false,slide:false,interact:false,reload:false,swap:false,gadget:false,melee:false,grenade:false,tactical:false,slot:undefined};}drain();if(mode==='playing'||mode==='dead')this.renderer.update(this.sim,dt,padActive?padPointer:this.input.activePointer);if(time-lastHud>70&&mode==='playing'){lastHud=time;hud();}}
 }
 function renderType(){const choice=new URLSearchParams(location.search).get('renderer');if(choice==='canvas')return Phaser.CANVAS;if(choice==='webgl')return Phaser.WEBGL;
  try{const testCanvas=document.createElement('canvas'),gl=testCanvas.getContext('webgl',{failIfMajorPerformanceCaveat:true});if(!gl)return Phaser.CANVAS;const ext=gl.getExtension('WEBGL_debug_renderer_info'),name=ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):'';const software=/swiftshader|llvmpipe|software/i.test(name);gl.getExtension('WEBGL_lose_context')?.loseContext();return software?Phaser.CANVAS:Phaser.AUTO;}catch{return Phaser.CANVAS;}}
 try{new Phaser.Game({type:renderType(),parent:'game',backgroundColor:'#252d24',scene:FieldScene,scale:{mode:Phaser.Scale.RESIZE,width:window.innerWidth,height:window.innerHeight},render:{antialias:true,pixelArt:false,roundPixels:false,powerPreference:'high-performance'},fps:{target:60,forceSetTimeOut:false},audio:{disableWebAudio:false},input:{keyboard:false}});}catch(err){$('load-text').textContent='COULD NOT INITIALIZE THE GAME. PLEASE REFRESH.';console.error(err);}
})();
